import React from "react";

export function DemoEvidenceBanner({
  message = "This evidence was generated by an explicit local engineering scenario. It does not represent live market data feeds or authorized execution authority.",
}: {
  message?: string;
}) {
  return (
    <div className="demo-evidence-banner" role="status" aria-label="Synthetic Demo Evidence Banner">
      <div className="demo-banner-header">
        <span className="demo-badge">SYNTHETIC DEMO EVIDENCE</span>
        <span className="demo-badge-sub">ENGINEERING TEST SCENARIO</span>
      </div>
      <p className="demo-banner-message">{message}</p>
    </div>
  );
}
