import { loadDashboardConfig, resolveDashboardOperatorToken } from "./dashboard-config";
import {
  type CommandCenterEvidence, type EvidenceResult, type FeatureDefinition, type FeatureMaterializationPage,
  type NewsEventPage, type PortfolioConstruction, type RegimeRun, type SignalPage, type SreOverview, type StrategyScorecard, readEvidence,
} from "./operator-contracts";

export const dynamic = "force-dynamic";

type DataHealth = { provider: string; healthy: boolean; checked_at: string; consecutive_failures: number; reason: string | null };
type Cadence = { account_id: string; provider: string; due: boolean; overdue: boolean; last_successful_at: string | null; approved_by: string };
type StrategyCard = { strategy_version: string; family: string; hypothesis: string; required_datasets: string[]; feature_versions: string[]; cost_model_version: string; limitations: string[]; expected_regimes: string[]; failure_conditions: string[]; created_at: string };
type Experiment = { experiment_id: string; strategy_version: string; dataset_version: string; feature_versions: string[]; cost_model_version: string; parameters: Record<string, unknown>; created_at: string; report: Record<string, string | number | null> };
type Promotion = { status: string; reasons: string[]; held_out_periods: number; held_out_total_return: string | null; decided_at: string };
type Thesis = { as_of: string; thesis: { thesis_id: string; instrument_id: string; version: string; statement: string; status: string; catalysts: string[]; risks: string[]; evidence_ids: string[] }; valuations: { model_version: string; intrinsic_value_per_share: string; as_of: string }[]; company_research: { bull_case: string; base_case: string; bear_case: string; evidence_ids: string[] }[]; reviews: { outcome: string; reviewed_at: string }[] };
type InvestmentPortfolio = { portfolio_id: string; as_of: string; assessment: { total_value: string; approved: boolean; reasons: string[] }; holdings: { instrument_id: string; market_value: string; source_reference: string }[]; rebalance_decisions: { rationale: string; approved_by: string }[]; performance: { observed_at: string; net_asset_value: string; cumulative_return: string }[] };
type OperationalAlert = { alert_id: string; code: string; severity: string; resource: string; status: string; created_at: string };
type PaperOrder = { paper_only: true; intent_id: string; instrument_id: string; account_id: string; side: string; quantity: string; status: string; filled_quantity: string; average_fill_price: string | null; created_at: string; events: { event_id: string; event_type: string; occurred_at: string }[]; fills: { fill_id: string; external_fill_id: string; quantity: string; price: string; occurred_at: string }[] };
type Reconciliation = { paper_only: true; source: string; occurred_at: string; complete: boolean; discrepancies: string[]; reconciled_account: { evidence_id: string; healthy: boolean; as_of: string; buying_power: string } | null };

function utc(value: string | null | undefined): string {
  if (!value) return "UNAVAILABLE";
  const instant = new Date(value);
  return Number.isNaN(instant.valueOf()) ? "UNAVAILABLE" : instant.toISOString().replace(".000Z", "Z");
}

function stateText<T>(result: EvidenceResult<T>): string {
  return result.state === "AVAILABLE" ? "AVAILABLE" : `${result.state}: ${result.detail}`;
}

function authorityUrl(origin: string, target: string): string {
  return `${origin}/api/authorities?target=${encodeURIComponent(target)}`;
}

function EvidenceMeta({ source, asOf, version, limitations }: { source: string; asOf: string; version?: string; limitations?: string[] }) {
  return <details className="provenance"><summary>Evidence & provenance</summary><dl><dt>Source</dt><dd>{source}</dd><dt>As of (UTC)</dt><dd><time dateTime={asOf}>{utc(asOf)}</time></dd>{version ? <><dt>Version</dt><dd>{version}</dd></> : null}<dt>Limitations</dt><dd>{limitations?.join("; ") || "None recorded"}</dd></dl></details>;
}

export default async function Home() {
  const config = loadDashboardConfig();
  const origin = config.dashboardOrigin;
  const protectedApi = Boolean(config.apiBaseUrl && resolveDashboardOperatorToken(config));
  const evidenceTime = new Date().toISOString();
  const command = readEvidence<CommandCenterEvidence>(`${origin}/api/operator`, protectedApi, "Operator API credentials are not configured.");
  const dataHealth = readEvidence<DataHealth>(`${origin}/api/data-health?target=/data-health/return-providers/${encodeURIComponent(config.returnProvider ?? "")}`, Boolean(config.returnProvider && protectedApi), "Return provider is not selected or authorized.");
  const cadence = readEvidence<Cadence[]>(`${origin}/api/data-health?target=/data-health/return-ingestion/cadences`, Boolean(config.returnAccount && config.returnProvider && protectedApi), "Return account/provider evidence is not configured.");
  const strategy = readEvidence<StrategyCard>(`${origin}/api/research?target=/research/strategies/${encodeURIComponent(config.strategyId ?? "")}`, Boolean(config.strategyId && protectedApi), "Strategy research reference is not configured.");
  const experiment = readEvidence<Experiment>(`${origin}/api/research?target=/research/experiments/${encodeURIComponent(config.experimentId ?? "")}`, Boolean(config.experimentId && protectedApi), "Backtest experiment reference is not configured.");
  const promotion = readEvidence<Promotion>(`${origin}/api/research?target=/research/promotions/${encodeURIComponent(config.promotionDecisionId ?? "")}`, Boolean(config.promotionDecisionId && protectedApi), "Promotion decision reference is not configured.");
  const thesis = readEvidence<Thesis>(`${origin}/api/investments?target=/investments/theses/${encodeURIComponent(config.investmentThesisId ?? "")}`, Boolean(config.investmentThesisId && protectedApi), "Investment thesis reference is not configured.");
  const portfolio = readEvidence<InvestmentPortfolio>(`${origin}/api/investments?target=/investments/portfolios/${encodeURIComponent(config.investmentPortfolioId ?? "")}`, Boolean(config.investmentPortfolioId && protectedApi), "Investment portfolio reference is not configured.");
  const alerts = readEvidence<OperationalAlert[]>(`${origin}/api/alerts`, protectedApi, "Operator alert credentials are not configured.");
  const paperOrder = readEvidence<PaperOrder>(`${origin}/api/paper-oms?target=/paper-oms/orders/${encodeURIComponent(config.paperOrderIntentId ?? "")}`, Boolean(config.paperOrderIntentId && protectedApi), "Paper order evidence reference is not configured.");
  const reconciliation = readEvidence<Reconciliation>(`${origin}/api/paper-oms?target=/paper-oms/accounts/${encodeURIComponent(config.paperAccountId ?? "")}/reconciliation`, Boolean(config.paperAccountId && protectedApi), "Paper account evidence reference is not configured.");
  const feature = readEvidence<FeatureDefinition>(authorityUrl(origin, `/operator-dashboard/feature-definitions/${encodeURIComponent(config.featureDefinitionId ?? "")}`), Boolean(config.featureDefinitionId && protectedApi), "Feature definition reference is not configured.");
  const featureMaterializations = readEvidence<FeatureMaterializationPage>(authorityUrl(origin, `/operator-dashboard/feature-materializations?feature_id=${encodeURIComponent(config.featureDefinitionId ?? "")}&instrument=${encodeURIComponent(config.featureInstrument ?? "")}&dataset_version=${encodeURIComponent(config.featureDatasetVersion ?? "")}&decision_time=${encodeURIComponent(config.featureDecisionTime ?? "")}&limit=20&offset=0`), Boolean(config.featureDefinitionId && config.featureInstrument && config.featureDatasetVersion && config.featureDecisionTime && protectedApi), "Feature materialization scope is not configured.");
  const signals = readEvidence<SignalPage>(authorityUrl(origin, `/operator-dashboard/signals?as_of=${encodeURIComponent(evidenceTime)}&limit=20&offset=0`), protectedApi, "Signal lifecycle authority is not configured.");
  const scorecard = readEvidence<StrategyScorecard>(authorityUrl(origin, `/operator-dashboard/strategy-scorecards/${encodeURIComponent(config.scorecardId ?? "")}`), Boolean(config.scorecardId && protectedApi), "Strategy scorecard reference is not configured.");
  const regime = readEvidence<RegimeRun>(authorityUrl(origin, `/operator-dashboard/regime-runs/${encodeURIComponent(config.regimeRunId ?? "")}`), Boolean(config.regimeRunId && protectedApi), "Regime run reference is not configured.");
  const construction = readEvidence<PortfolioConstruction>(authorityUrl(origin, `/operator-dashboard/portfolio-construction-runs/${encodeURIComponent(config.portfolioConstructionRunId ?? "")}`), Boolean(config.portfolioConstructionRunId && protectedApi), "Portfolio construction run reference is not configured.");
  const news = readEvidence<NewsEventPage>(authorityUrl(origin, `/operator-dashboard/news-events?limit=20&offset=0${config.newsInstrument ? `&instrument=${encodeURIComponent(config.newsInstrument)}` : ""}`), protectedApi, "News/event authority is not configured.");
  const sre = readEvidence<SreOverview>(authorityUrl(origin, `/operator-dashboard/sre-overview${config.sreServiceVersionId ? `?service_version_id=${encodeURIComponent(config.sreServiceVersionId)}` : ""}`), protectedApi, "SRE authority is not configured.");
  return <Dashboard command={await command} dataHealth={await dataHealth} cadence={await cadence} strategy={await strategy} experiment={await experiment} promotion={await promotion} thesis={await thesis} portfolio={await portfolio} alerts={await alerts} paperOrder={await paperOrder} reconciliation={await reconciliation} feature={await feature} featureMaterializations={await featureMaterializations} signals={await signals} scorecard={await scorecard} regime={await regime} construction={await construction} news={await news} sre={await sre} />;
}

function Dashboard({ command, dataHealth, cadence, strategy, experiment, promotion, thesis, portfolio, alerts, paperOrder, reconciliation, feature, featureMaterializations, signals, scorecard, regime, construction, news, sre }: { command: EvidenceResult<CommandCenterEvidence>; dataHealth: EvidenceResult<DataHealth>; cadence: EvidenceResult<Cadence[]>; strategy: EvidenceResult<StrategyCard>; experiment: EvidenceResult<Experiment>; promotion: EvidenceResult<Promotion>; thesis: EvidenceResult<Thesis>; portfolio: EvidenceResult<InvestmentPortfolio>; alerts: EvidenceResult<OperationalAlert[]>; paperOrder: EvidenceResult<PaperOrder>; reconciliation: EvidenceResult<Reconciliation>; feature: EvidenceResult<FeatureDefinition>; featureMaterializations: EvidenceResult<FeatureMaterializationPage>; signals: EvidenceResult<SignalPage>; scorecard: EvidenceResult<StrategyScorecard>; regime: EvidenceResult<RegimeRun>; construction: EvidenceResult<PortfolioConstruction>; news: EvidenceResult<NewsEventPage>; sre: EvidenceResult<SreOverview> }) {
  const health = dataHealth.state === "AVAILABLE" ? dataHealth.value : undefined;
  const schedule = cadence.state === "AVAILABLE" ? cadence.value[0] : undefined;
  const strategyCard = strategy.state === "AVAILABLE" ? strategy.value : undefined;
  const backtest = experiment.state === "AVAILABLE" ? experiment.value : undefined;
  const investment = thesis.state === "AVAILABLE" ? thesis.value : undefined;
  const investmentPortfolio = portfolio.state === "AVAILABLE" ? portfolio.value : undefined;
  const order = paperOrder.state === "AVAILABLE" ? paperOrder.value : undefined;
  const account = reconciliation.state === "AVAILABLE" ? reconciliation.value : undefined;
  const commandEvidence = command.state === "AVAILABLE" ? command.value : undefined;
  const alertRows = alerts.state === "AVAILABLE" ? alerts.value : undefined;
  const featureDefinition = feature.state === "AVAILABLE" ? feature.value : undefined;
  const materializations = featureMaterializations.state === "AVAILABLE" ? featureMaterializations.value : undefined;
  const signalEvidence = signals.state === "AVAILABLE" ? signals.value : undefined;
  const scorecardEvidence = scorecard.state === "AVAILABLE" ? scorecard.value : undefined;
  const regimeEvidence = regime.state === "AVAILABLE" ? regime.value : undefined;
  const constructionEvidence = construction.state === "AVAILABLE" ? construction.value : undefined;
  const newsEvidence = news.state === "AVAILABLE" ? news.value : undefined;
  const sreEvidence = sre.state === "AVAILABLE" ? sre.value : undefined;
  const latestValuation = investment?.valuations.at(-1); const company = investment?.company_research.at(-1); const latestPerformance = investmentPortfolio?.performance.at(-1);
  return <main id="main-content"><header><div><p className="eyebrow">PRIVATE READ-ONLY OPERATOR WORKSPACE</p><h1>Command Center</h1><p>Rendered evidence time: <time dateTime={new Date().toISOString()}>{utc(new Date().toISOString())}</time> UTC</p></div><span className="badge">LIVE TRADING: DISABLED</span></header>
    <nav aria-label="Operator workspaces"><a href="#data-sources">Data Sources</a><a href="#data-health">Data Health</a><a href="#instrument">Instruments</a><a href="#features">Features</a><a href="#signals">Signals</a><a href="#strategy">Strategy Lab</a><a href="#backtest">Validation</a><a href="#scorecard">Scorecard</a><a href="#regime">Regime</a><a href="#portfolio">Portfolio</a><a href="#investment">Investment</a><a href="#news">News</a><a href="#paper-oms">Paper OMS</a><a href="#operations">Operations</a><a href="#audit">Audit</a></nav>
    <section className="cards" aria-label="Authoritative command summary"><article className="card"><p>PLATFORM</p><strong>{commandEvidence?.platform_mode ?? stateText(command)}</strong><small>Live trading: DISABLED</small><a href="#command">View platform evidence</a></article><article className="card"><p>DATA</p><strong>{commandEvidence?.states.find((item) => item.id === "features")?.status ?? (health ? (health.healthy ? "AVAILABLE" : "BLOCKED") : dataHealth.state)}</strong><small>Provider, Data Health, dataset and feature state</small><a href="#features">View feature evidence</a></article><article className="card"><p>RESEARCH</p><strong>{commandEvidence?.states.find((item) => item.id === "scorecard")?.status ?? scorecard.state}</strong><small>{scorecardEvidence?.evidence_classification ?? "Eligibility evidence unavailable"}</small><a href="#scorecard">View scorecard evidence</a></article><article className="card"><p>PORTFOLIO</p><strong>{commandEvidence?.states.find((item) => item.id === "portfolio-construction")?.status ?? construction.state}</strong><small>{constructionEvidence ? `${constructionEvidence.sleeves.filter((item) => item.rejected).length} rejected; ${constructionEvidence.sleeves.filter((item) => item.adjustment_reasons.length).length} reduced` : "Construction review unavailable"}</small><a href="#portfolio">View construction evidence</a></article><article className="card"><p>INVESTMENT</p><strong>{investment?.thesis.status ?? thesis.state}</strong><small>{alertRows ? `${alertRows.length} pending operator alerts` : "Alert evidence unavailable"}</small><a href="#investment">View investment evidence</a></article><article className="card"><p>NEWS</p><strong>{commandEvidence?.states.find((item) => item.id === "news")?.status ?? newsEvidence?.provider_state ?? news.state}</strong><small>Provider authorization and latest persisted event</small><a href="#news">View event evidence</a></article><article className="card"><p>OPERATIONS</p><strong>{commandEvidence?.states.find((item) => item.id === "operations")?.status ?? sre.state}</strong><small>PostgreSQL, reconciliation, recovery, incidents and kill switches</small><a href="#operations">View SRE evidence</a></article></section>
    <section className="grid">
      <article id="command"><h2>Command Center Evidence</h2>{commandEvidence ? <><dl><dt>Contract version</dt><dd>{commandEvidence.version}</dd><dt>Platform mode</dt><dd>{commandEvidence.platform_mode}</dd><dt>Live trading</dt><dd>{commandEvidence.live_trading_enabled ? "ENABLED" : "DISABLED"}</dd>{commandEvidence.states.map((item) => <><dt key={`${item.id}-label`}>{item.id}</dt><dd key={item.id}>{item.status}: {item.freshness}</dd></>)}</dl><EvidenceMeta source={commandEvidence.source} asOf={commandEvidence.as_of} version={commandEvidence.version} limitations={commandEvidence.limitations} /></> : <p className="empty-state">{stateText(command)}</p>}<span className="status">READ ONLY</span></article>
      <article id="data-sources"><h2>Data Sources / Providers</h2><p>Provider credentials and terms never enter the browser.</p><dl><dt>Provider</dt><dd>{health?.provider ?? "EXTERNAL_BLOCKED"}</dd><dt>Authorization / terms</dt><dd>{health ? "Configured record only; provider activation not asserted" : "EXTERNAL_BLOCKED"}</dd><dt>Health / freshness</dt><dd>{health ? `${health.healthy ? "HEALTHY" : "BLOCKING"}; checked ${utc(health.checked_at)}` : stateText(dataHealth)}</dd><dt>Checkpoint / dataset version</dt><dd>UNAVAILABLE</dd></dl><span className="status">{health ? "READ ONLY" : "EXTERNAL_BLOCKED"}</span></article>
      <article id="data-health"><h2>Data Health</h2><p>Blocking evidence is not bypassable from this console.</p><dl><dt>Assessment</dt><dd>{health ? `return-provider:${health.provider}` : "UNAVAILABLE"}</dd><dt>Severity / action</dt><dd>{health ? (health.healthy ? "HEALTHY / ALLOW" : "BLOCKING / REVIEW REQUIRED") : dataHealth.state}</dd><dt>Failures</dt><dd>{health?.consecutive_failures.toString() ?? "UNAVAILABLE"}</dd><dt>Reason</dt><dd>{health?.reason ?? "UNAVAILABLE"}</dd><dt>Cadence / last success</dt><dd>{schedule ? `${schedule.overdue ? "STALE" : schedule.due ? "DUE" : "CURRENT"}; ${utc(schedule.last_successful_at)}` : stateText(cadence)}</dd></dl>{health ? <EvidenceMeta source={`return-provider:${health.provider}`} asOf={health.checked_at} version="return-health-v1" limitations={["Dataset-level assessment is unavailable through this configured source."]} /> : null}<span className="status">READ ONLY</span></article>
      <article id="instrument"><h2>Instrument Workstation</h2><p>Point-in-time canonical mappings, lifecycle, sessions, and corporate actions require a configured instrument authority.</p><p className="empty-state">EXTERNAL_BLOCKED: no instrument lookup is configured. Ambiguous symbols are never guessed.</p><span className="status">EXTERNAL_BLOCKED / READ ONLY</span></article>
      <article id="features"><h2>Feature Authority</h2><p>Feature values are displayed exactly as materialized by the point-in-time PostgreSQL authority; the frontend never recomputes them.</p>{featureDefinition ? <><dl><dt>Definition / version</dt><dd>{featureDefinition.feature_name} / {featureDefinition.semantic_version}</dd><dt>Family / status</dt><dd>{featureDefinition.family} / {featureDefinition.status}</dd><dt>Required dataset / fields</dt><dd>{featureDefinition.required_dataset_types.join(", ")} / {featureDefinition.required_fields.join(", ")}</dd><dt>Frequency / timestamp semantics / lookback</dt><dd>{featureDefinition.frequency} / {featureDefinition.timestamp_semantics} / {featureDefinition.lookback}</dd><dt>Policies</dt><dd>Missing: {featureDefinition.missing_value_policy}; outlier: {featureDefinition.outlier_policy}; leakage: {featureDefinition.leakage_policy}</dd><dt>Units / calculation</dt><dd>{featureDefinition.units} / {featureDefinition.calculation_version}</dd></dl><EvidenceMeta source="PostgreSQL Feature Authority" asOf={featureDefinition.created_at} version={featureDefinition.semantic_version} /></> : <p className="empty-state">{stateText(feature)}</p>}{materializations?.items.length ? <table><caption>Point-in-time materializations as of {utc(materializations.decision_time)}</caption><thead><tr><th>Instrument / dataset</th><th>Event / knowledge / computed</th><th>Value</th><th>Quality / provenance</th></tr></thead><tbody>{materializations.items.map((item) => <tr key={item.materialization_id}><td>{item.instrument}<br />{item.dataset_version}</td><td>{utc(item.event_time)}<br />{utc(item.knowledge_time)}<br />{utc(item.computed_time)}</td><td>{item.value ?? "UNAVAILABLE"}</td><td>{item.quality_state}<br />{item.content_hash}<br />{item.source_manifest.join(", ")}</td></tr>)}</tbody></table> : <p className="empty-state">UNAVAILABLE: {materializations ? "no authorized materialization matched this bounded PIT scope; zero was not substituted." : stateText(featureMaterializations)}</p>}<span className="status">{materializations?.items.length ? "AVAILABLE" : "UNAVAILABLE"} / READ ONLY</span></article>
      <article id="signals"><h2>Signal Explorer</h2><p>Point-in-time, reasoned lifecycle evidence only. No control here can create an order, activate a strategy, or contact a broker.</p>{signalEvidence?.items.length ? <><table><caption>Signal lifecycle as of {utc(signalEvidence.as_of)}</caption><thead><tr><th>Signal / instrument</th><th>Status / expiry</th><th>Strength / confidence / data</th><th>Reason / explanation</th></tr></thead><tbody>{signalEvidence.items.map((item) => <tr key={item.signal_id}><td>{item.signal_id}<br />{item.instrument}<br />{item.strategy_version} / {item.direction}</td><td>{item.status} / {item.expiry_state}<br />created {utc(item.created_at)}<br />expires {utc(item.expires_at)}</td><td>{item.strength} / {item.confidence} / {item.data_quality_score}<br />passed {item.passed_stages.join(", ") || "none"}<br />failed {item.failed_stages.join(", ") || "none"}</td><td>{item.latest_reason}<br />{item.explanation}<br />Contradicting: {item.contradicting_evidence.join("; ") || "none recorded"}</td></tr>)}</tbody></table>{signalEvidence.items.map((item) => <details key={`${item.signal_id}-timeline`}><summary>Lifecycle for {item.signal_id}</summary><ol>{item.lifecycle.map((event) => <li key={event.event_id}>{event.from_status} → {event.to_status} at {utc(event.occurred_at)} by {event.actor}: {event.reason}; evidence {event.evidence_references.join(", ") || "none"}</li>)}</ol></details>)}</> : <p className="empty-state">{signalEvidence ? `${signalEvidence.state}: no signal matched this bounded point-in-time scope.` : stateText(signals)}</p>}<span className="status">RESEARCH / PAPER ONLY / READ ONLY / NO AUTOMATIC AUTHORITY</span></article>
      <article id="strategy"><h2>Strategy Laboratory</h2>{strategyCard ? <><dl><dt>Family / version</dt><dd>{strategyCard.family} / {strategyCard.strategy_version}</dd><dt>Hypothesis</dt><dd>{strategyCard.hypothesis}</dd><dt>Features / datasets</dt><dd>{strategyCard.feature_versions.join(", ")} / {strategyCard.required_datasets.join(", ")}</dd><dt>Regimes / failures</dt><dd>{strategyCard.expected_regimes.join(", ")} / {strategyCard.failure_conditions.join(", ")}</dd><dt>Evidence classification</dt><dd>{strategyCard.family.toLowerCase().includes("trend") ? "SYNTHETIC_ENGINEERING_EVIDENCE_ONLY" : "RESEARCH EVIDENCE ONLY"}</dd></dl><EvidenceMeta source="strategy-registry" asOf={strategyCard.created_at} version={strategyCard.strategy_version} limitations={strategyCard.limitations} /></> : <p className="empty-state">{stateText(strategy)}</p>}<span className="status">RESEARCH ONLY / READ ONLY</span></article>
      <article id="backtest"><h2>Backtest / Validation</h2>{backtest ? <><dl><dt>Strategy / dataset</dt><dd>{backtest.strategy_version} / {backtest.dataset_version}</dd><dt>Features / cost model</dt><dd>{backtest.feature_versions.join(", ")} / {backtest.cost_model_version}</dd><dt>Return</dt><dd>{String(backtest.report.total_return ?? "UNAVAILABLE")}</dd><dt>Independent accounting</dt><dd>{backtest.report.independent_bar_engine_reconciled === "1" ? "RECONCILED" : "UNAVAILABLE OR DIVERGENT"}</dd><dt>Walk-forward</dt><dd>{String(backtest.report.walk_forward_status ?? "UNAVAILABLE")}</dd><dt>Costs / capacity / latency</dt><dd>{String(backtest.report.pessimistic_cost_multiplier ?? "UNAVAILABLE")} / UNAVAILABLE / UNAVAILABLE</dd><dt>Promotion</dt><dd>{promotion.state === "AVAILABLE" ? `${promotion.value.status}: ${promotion.value.reasons.join(", ")}` : stateText(promotion)}</dd></dl><EvidenceMeta source="experiment-store" asOf={backtest.created_at} version={backtest.cost_model_version} limitations={["No aggregate score hides unavailable validation evidence."]} /></> : <p className="empty-state">{stateText(experiment)}</p>}<span className="status">HISTORICAL / RESEARCH ONLY</span></article>
      <article id="scorecard"><h2>Strategy Scorecard V2</h2><p>No opaque aggregate score is used. Metric evidence state is independent from workspace availability.</p>{scorecardEvidence ? <><p className="warning">{scorecardEvidence.evidence_classification}</p><dl><dt>Scorecard / strategy</dt><dd>{scorecardEvidence.scorecard_id} / {scorecardEvidence.strategy_version}</dd><dt>Research / dataset / features / costs</dt><dd>{scorecardEvidence.research_run_id} / {scorecardEvidence.dataset_version} / {scorecardEvidence.feature_versions.join(", ")} / {scorecardEvidence.cost_model_version}</dd><dt>Evaluated / knowledge cutoff</dt><dd>{utc(scorecardEvidence.evaluated_at)} / {utc(scorecardEvidence.knowledge_cutoff)}</dd><dt>Status / validation package</dt><dd>{scorecardEvidence.status} / {scorecardEvidence.validation_package_id ?? "UNAVAILABLE"}</dd><dt>Evidence hash</dt><dd>{scorecardEvidence.content_hash}</dd></dl>{scorecardEvidence.groups.map((group) => <section key={group.name} aria-labelledby={`scorecard-${group.name}`}><h3 id={`scorecard-${group.name}`}>{group.name}</h3>{group.metrics.length ? <table><thead><tr><th>Metric</th><th>Value / unit</th><th>Evidence state</th><th>Reference</th></tr></thead><tbody>{group.metrics.map((metric) => <tr key={metric.metric_id}><td>{metric.name}</td><td>{metric.value ?? "UNAVAILABLE"} {metric.unit}</td><td>{metric.evidence_state}</td><td>{metric.evidence_reference}</td></tr>)}</tbody></table> : <p className="empty-state">UNAVAILABLE</p>}</section>)}<section aria-labelledby="scorecard-complexity"><h3 id="scorecard-complexity">COMPLEXITY</h3>{scorecardEvidence.complexity_components.map((item) => <p key={item.component_id}>{item.name}: {item.value ?? "UNAVAILABLE"} ({item.formula_version}) — {item.rationale}</p>)}</section><EvidenceMeta source="PostgreSQL Strategy Scorecard V2" asOf={scorecardEvidence.evaluated_at} version={scorecardEvidence.schema_version} limitations={scorecardEvidence.limitations} /></> : <p className="empty-state">{stateText(scorecard)}</p>}<span className="status">RESEARCH EVIDENCE / READ ONLY</span></article>
      <article id="regime"><h2>Regime Workspace</h2><p className="warning">REGIME MAY REDUCE OR BLOCK RISK. REGIME CANNOT INCREASE GLOBAL RISK LIMITS.</p>{regimeEvidence ? <><dl><dt>Assessment / model / rule</dt><dd>{regimeEvidence.regime_assessment_id} / {regimeEvidence.model_version} / {regimeEvidence.rule_version}</dd><dt>Dataset / instrument</dt><dd>{regimeEvidence.dataset_version} / {regimeEvidence.instrument}</dd><dt>As of / knowledge time</dt><dd>{utc(regimeEvidence.as_of_timestamp)} / {utc(regimeEvidence.knowledge_timestamp)}</dd><dt>Status / evidence hash</dt><dd>{regimeEvidence.status} / {regimeEvidence.evidence_hash}</dd></dl><table><thead><tr><th>Dimension / method</th><th>State probabilities</th><th>Uncertainty</th><th>Evidence</th></tr></thead><tbody>{regimeEvidence.dimensions.map((item) => <tr key={item.observation_id}><td>{item.dimension}<br />{item.method}</td><td>{item.probabilities.map((probability) => `${probability.state} ${probability.probability}`).join("; ") || "UNAVAILABLE"}</td><td>{item.uncertainty ?? "UNAVAILABLE"}</td><td>{item.evidence_state}; {item.content_hash}</td></tr>)}</tbody></table><h3>Eligibility / reduction effects</h3>{regimeEvidence.risk_effects.length ? regimeEvidence.risk_effects.map((item) => <p key={item.candidate_id}>{item.action}: {item.current_risk_multiplier} → {item.proposed_risk_multiplier}; maximum {item.preapproved_maximum}; {item.status} {item.reasons.join(", ")}</p>) : <p className="empty-state">UNAVAILABLE: no reduction candidate is bound to this run.</p>}<EvidenceMeta source="PostgreSQL Regime Engine V2" asOf={regimeEvidence.as_of_timestamp} version={regimeEvidence.model_version} limitations={regimeEvidence.limitations} /></> : <p className="empty-state">{stateText(regime)}</p>}<span className="status">RESEARCH ONLY / NO RISK-INCREASE CONTROL</span></article>
      <article id="portfolio"><h2>Portfolio Construction</h2><p>Review-only requested and constrained allocations. This workspace has no apply or execution action.</p>{constructionEvidence ? <><dl><dt>Run / policy</dt><dd>{constructionEvidence.portfolio_construction_run_id} / {constructionEvidence.policy_version}</dd><dt>Status / constructed</dt><dd>{constructionEvidence.status} / {utc(constructionEvidence.constructed_at)}</dd><dt>Equity / target volatility</dt><dd>{constructionEvidence.equity} / {constructionEvidence.target_volatility ?? "UNAVAILABLE"}</dd><dt>Cash / gross / net</dt><dd>{constructionEvidence.cash_weight} / {constructionEvidence.gross_weight} / {constructionEvidence.net_weight}</dd><dt>Volatility / stressed</dt><dd>{constructionEvidence.portfolio_volatility} / {constructionEvidence.stressed_volatility}</dd><dt>Covariance evidence</dt><dd>{constructionEvidence.covariance.classification}; {constructionEvidence.covariance.dataset_version}; {constructionEvidence.covariance.observations} observations; uncertainty {constructionEvidence.covariance.uncertainty}</dd><dt>Risk gate</dt><dd>{constructionEvidence.risk_gate_approved ? "REVIEW ELIGIBLE" : "BLOCKED"}: {constructionEvidence.risk_gate_reasons.join(", ")}</dd></dl><table><thead><tr><th>Sleeve</th><th>Requested / review</th><th>Risk / marginal / component</th><th>Reductions / rejection</th></tr></thead><tbody>{constructionEvidence.sleeves.map((item) => <tr key={item.sleeve_input_id}><td>{item.strategy_key}</td><td>{item.requested_allocation} / {item.review_allocation ?? "REJECTED"}</td><td>{item.risk_budget} / {item.marginal_risk ?? "UNAVAILABLE"} / {item.component_risk ?? "UNAVAILABLE"}</td><td>capacity {item.capacity_weight}; liquidity {item.liquidity_score}; drawdown {item.drawdown}; regime {item.regime_current_multiplier}→{item.regime_proposed_multiplier}; {item.adjustment_reasons.join(", ") || "none"}</td></tr>)}</tbody></table><h3>Constraints</h3>{constructionEvidence.constraints.map((item) => <p key={item.constraint_id}>{item.name}: {item.state}; observed {item.observed ?? "UNAVAILABLE"}; limit {item.limit ?? "UNAVAILABLE"}; {item.reasons.join(", ")}</p>)}<EvidenceMeta source="PostgreSQL Portfolio Construction V2" asOf={constructionEvidence.constructed_at} version={constructionEvidence.policy_version} limitations={constructionEvidence.limitations} /></> : <p className="empty-state">{stateText(construction)}</p>}<span className="status">REVIEW ONLY / NO EXECUTION ACTION</span></article>
      <article id="investment"><h2>Investment Workspace</h2><p>NOT A REAL INVESTMENT RECOMMENDATION. Long-horizon research is separate from trading.</p>{investment ? <><dl><dt>Instrument / thesis</dt><dd>{investment.thesis.instrument_id} / {investment.thesis.statement}</dd><dt>Status / version</dt><dd>{investment.thesis.status} / {investment.thesis.version}</dd><dt>Catalysts / risks</dt><dd>{investment.thesis.catalysts.join(", ")} / {investment.thesis.risks.join(", ")}</dd><dt>Bear / base / bull</dt><dd>{company ? `${company.bear_case} / ${company.base_case} / ${company.bull_case}` : "UNAVAILABLE"}</dd><dt>Valuation</dt><dd>{latestValuation ? `${latestValuation.intrinsic_value_per_share}; ${latestValuation.model_version}` : "UNAVAILABLE"}</dd><dt>Latest review</dt><dd>{investment.reviews.at(-1)?.outcome ?? "UNAVAILABLE"}</dd></dl><EvidenceMeta source="investment-store" asOf={investment.as_of} version={investment.thesis.version} limitations={["Fixture valuation is not investment advice."]} /></> : <p className="empty-state">{stateText(thesis)}</p>}{investmentPortfolio ? <dl><dt>Portfolio / review state</dt><dd>{investmentPortfolio.portfolio_id} / {investmentPortfolio.assessment.approved ? "WITHIN LIMITS" : investmentPortfolio.assessment.reasons.join(", ")}</dd><dt>Value / NAV / return</dt><dd>{investmentPortfolio.assessment.total_value} / {latestPerformance ? `${latestPerformance.net_asset_value} / ${latestPerformance.cumulative_return}` : "UNAVAILABLE"}</dd><dt>Holdings provenance</dt><dd>{investmentPortfolio.holdings.map((item) => `${item.instrument_id}: ${item.source_reference}`).join("; ") || "EMPTY"}</dd><dt>Rebalance candidate</dt><dd>{investmentPortfolio.rebalance_decisions.at(-1)?.rationale ?? "EMPTY"}</dd></dl> : <p className="empty-state">{stateText(portfolio)}</p>}<span className="status">REVIEW ONLY / NO BUY OR SELL</span></article>
      <article id="news"><h2>News / Event Intelligence</h2><p>Persisted correction-aware research evidence is never presented as a live feed and cannot create an order.</p><p className="warning">{newsEvidence?.provider_state ?? "EXTERNAL_BLOCKED"}{newsEvidence?.provider_state === "EXTERNAL_BLOCKED" ? ": no external provider is authorized or activated." : ""}</p>{newsEvidence?.items.length ? newsEvidence.items.map((item) => <section key={item.event_id} aria-labelledby={`news-${item.event_id}`}><h3 id={`news-${item.event_id}`}>{item.headline}</h3><dl><dt>Source / terms / rights</dt><dd>{item.source} / {item.source_terms_version} / {item.rights_state}; provider activated: {item.provider_activated ? "YES" : "NO"}</dd><dt>Published / ingested / correction</dt><dd>{utc(item.published_at)} / {utc(item.ingested_at)} / {utc(item.correction_or_retraction_at)}</dd><dt>Category / novelty / credibility</dt><dd>{item.category} / {item.novelty} / {item.credibility ?? "UNAVAILABLE"}</dd><dt>Uncertainty / urgency / horizon</dt><dd>{item.uncertainty} / {item.urgency} / {item.horizon}</dd><dt>Revision / chain</dt><dd>{item.revision_kind} #{item.revision}; {item.correction_chain.map((link) => `${link.relation} ${link.predecessor_id}→${link.successor_id}`).join("; ") || "no predecessor/replacement"}</dd><dt>Linked instruments</dt><dd>{item.entities.map((entity) => `${entity.instrument} (${entity.method}, ${entity.confidence})`).join("; ") || "UNAVAILABLE"}</dd><dt>Fingerprint / provenance</dt><dd>{item.content_fingerprint} / {item.provenance_reference}</dd></dl></section>) : <p className="empty-state">{newsEvidence ? `${newsEvidence.state}: no persisted event matched this scope.` : stateText(news)}</p>}<span className="status">{newsEvidence?.provider_state ?? "EXTERNAL_BLOCKED"} / READ ONLY / NOT LIVE NEWS</span></article>
      <article id="paper-oms"><h2>Paper OMS</h2><p>Paper lifecycle and reconciliation evidence only; this page cannot submit an order.</p>{order ? <><dl><dt>Intent / instrument</dt><dd>{order.intent_id} / {order.instrument_id}</dd><dt>Status / quantity / filled</dt><dd>{order.status} / {order.quantity} / {order.filled_quantity}</dd><dt>Partial fills</dt><dd>{order.fills.map((fill) => `${fill.external_fill_id}: ${fill.quantity} @ ${fill.price}`).join("; ") || "EMPTY"}</dd><dt>Lifecycle</dt><dd>{order.events.map((event) => `${event.event_type} @ ${utc(event.occurred_at)}`).join("; ")}</dd><dt>Reconciliation</dt><dd>{account ? `${account.complete ? "COMPLETE" : account.discrepancies.join(", ")}; ${account.source}; ${utc(account.occurred_at)}` : stateText(reconciliation)}</dd></dl><EvidenceMeta source="paper-oms" asOf={order.created_at} version="paper-oms-v1" limitations={["Paper-only evidence; no broker execution capability."]} /></> : <p className="empty-state">{stateText(paperOrder)}</p>}<span className="status">PAPER ONLY / READ ONLY</span></article>
      <article id="operations"><h2>Operations / SRE</h2><p>TARGET and MEASURED are distinct. Candidate targets are never presented as achieved operational evidence.</p>{sreEvidence ? <><dl><dt>Subsystem / version / environment</dt><dd>{sreEvidence.subsystem} / {sreEvidence.version} / {sreEvidence.environment}</dd><dt>PostgreSQL / provider</dt><dd>{sreEvidence.postgres_state} / {sreEvidence.provider_state}</dd><dt>Ingestion / dataset / feature freshness</dt><dd>{sreEvidence.ingestion_checkpoint_freshness} / {sreEvidence.dataset_freshness} / {sreEvidence.feature_freshness}</dd><dt>Research / signal / risk</dt><dd>{sreEvidence.research_job_health} / {sreEvidence.signal_freshness} / {sreEvidence.risk_status}</dd><dt>Reconciliation / backup-restore / kill switch</dt><dd>{sreEvidence.reconciliation_status} / {sreEvidence.backup_restore_status} / {sreEvidence.kill_switch_state}</dd></dl><h3>SLO evidence</h3><table><thead><tr><th>Indicator</th><th>TARGET</th><th>MEASURED</th><th>Evidence state</th></tr></thead><tbody>{sreEvidence.slos.map((item) => <tr key={item.slo_policy_version_id}><td>{item.name}: {item.indicator}</td><td>{item.target}</td><td>{item.measured_value ?? "UNAVAILABLE"}</td><td>{item.measured_state}; {item.claim_status ?? "NO MEASUREMENT"}</td></tr>)}</tbody></table><h3>Incidents</h3>{sreEvidence.incidents.length ? sreEvidence.incidents.map((item) => <p key={item.incident_id}>{item.incident_id}: {item.severity} {item.subsystem}; opened {utc(item.opened_at)}; acknowledged {utc(item.acknowledged_at)}; resolved {utc(item.resolved_at)}; {item.status}; {item.reason}; {item.evidence_reference}</p>) : <p className="empty-state">UNAVAILABLE: no persisted incident evidence.</p>}<h3>Failure / recovery drills</h3>{sreEvidence.failure_drills.map((item) => <p key={item.drill_run_id}>{item.scenario}: {item.passed ? "PASSED" : "FAILED"}; expected {item.expected_protection}; measured {item.observed_protection}; {item.evidence_reference}</p>)}</> : <p className="empty-state">{stateText(sre)}</p>}<span className="status">READ ONLY / TARGET ≠ MEASURED</span></article>
      <article id="audit"><h2>Audit</h2><p>Audit evidence is immutable and read-only: actor, action, domain object, version, timestamp, decision, reasons, and evidence IDs belong to protected backend records.</p><dl><dt>Alert evidence</dt><dd>{alertRows?.map((item) => `${item.alert_id}: ${item.severity} ${item.code} @ ${utc(item.created_at)}`).join("; ") || stateText(alerts)}</dd><dt>Mutation control</dt><dd>NO MUTATION ROUTE EXPOSED BY THIS DASHBOARD</dd></dl><span className="status">READ ONLY</span></article>
    </section><footer>Live trading is deliberately unavailable. This console has no live-execution, risk-override, kill-switch-bypass, or automatic strategy-activation control.</footer></main>;
}
