import { loadDashboardConfig, resolveDashboardOperatorToken } from "./dashboard-config";
import { type CommandCenterEvidence, type EvidenceResult, readEvidence } from "./operator-contracts";

export const dynamic = "force-dynamic";

type DataHealth = { provider: string; healthy: boolean; checked_at: string; consecutive_failures: number; reason: string | null };
type Cadence = { account_id: string; provider: string; due: boolean; overdue: boolean; last_successful_at: string | null; approved_by: string };
type StrategyCard = { strategy_version: string; family: string; hypothesis: string; required_datasets: string[]; feature_versions: string[]; cost_model_version: string; limitations: string[]; expected_regimes: string[]; failure_conditions: string[]; created_at: string };
type Experiment = { experiment_id: string; strategy_version: string; dataset_version: string; feature_versions: string[]; cost_model_version: string; parameters: Record<string, unknown>; created_at: string; report: Record<string, string | number | null> };
type Promotion = { status: string; reasons: string[]; held_out_periods: number; held_out_total_return: string | null; decided_at: string };
type Thesis = { as_of: string; thesis: { thesis_id: string; instrument_id: string; version: string; statement: string; status: string; catalysts: string[]; risks: string[]; evidence_ids: string[] }; valuations: { model_version: string; intrinsic_value_per_share: string; as_of: string }[]; company_research: { bull_case: string; base_case: string; bear_case: string; evidence_ids: string[] }[]; reviews: { outcome: string; reviewed_at: string }[] };
type InvestmentPortfolio = { portfolio_id: string; as_of: string; assessment: { total_value: string; approved: boolean; reasons: string[] }; holdings: { instrument_id: string; market_value: string; source_reference: string }[]; rebalance_decisions: { rationale: string; approved_by: string }[]; performance: { observed_at: string; net_asset_value: string; cumulative_return: string }[] };
type OperationalAlert = { alert_id: string; code: string; severity: string; resource: string; status: string; created_at: string };
type PaperOrder = { paper_only: true; intent_id: string; instrument_id: string; account_id: string; side: string; quantity: string; status: string; filled_quantity: string; average_fill_price: string | null; created_at: string; events: { event_id: string; event_type: string; occurred_at: string }[]; fills: { fill_id: string; external_fill_id: string; quantity: string; price: string; occurred_at: string }[] };
type Reconciliation = { paper_only: true; source: string; occurred_at: string; complete: boolean; discrepancies: string[]; reconciled_account: { evidence_id: string; healthy: boolean; as_of: string; buying_power: string } | null };

function utc(value: string | null | undefined): string {
  if (!value) return "UNAVAILABLE";
  const instant = new Date(value);
  return Number.isNaN(instant.valueOf()) ? "UNAVAILABLE" : instant.toISOString().replace(".000Z", "Z");
}

function stateText<T>(result: EvidenceResult<T>): string {
  return result.state === "AVAILABLE" ? "AVAILABLE" : `${result.state}: ${result.detail}`;
}

function EvidenceMeta({ source, asOf, version, limitations }: { source: string; asOf: string; version?: string; limitations?: string[] }) {
  return <details className="provenance"><summary>Evidence & provenance</summary><dl><dt>Source</dt><dd>{source}</dd><dt>As of (UTC)</dt><dd><time dateTime={asOf}>{utc(asOf)}</time></dd>{version ? <><dt>Version</dt><dd>{version}</dd></> : null}<dt>Limitations</dt><dd>{limitations?.join("; ") || "None recorded"}</dd></dl></details>;
}

function UnconfiguredWorkspace({ id, title, purpose, state = "EXTERNAL_BLOCKED" }: { id: string; title: string; purpose: string; state?: "EXTERNAL_BLOCKED" | "UNAVAILABLE" }) {
  return <article id={id}><h2>{title}</h2><p>{purpose}</p><p className="empty-state">{state}: no dashboard authority is configured for this durable evidence yet.</p><span className="status">{state} / READ ONLY</span></article>;
}

export default async function Home() {
  const config = loadDashboardConfig();
  const origin = config.dashboardOrigin;
  const protectedApi = Boolean(config.apiBaseUrl && resolveDashboardOperatorToken(config));
  const command = readEvidence<CommandCenterEvidence>(`${origin}/api/operator`, protectedApi, "Operator API credentials are not configured.");
  const dataHealth = readEvidence<DataHealth>(`${origin}/api/data-health?target=/data-health/return-providers/${encodeURIComponent(config.returnProvider ?? "")}`, Boolean(config.returnProvider && protectedApi), "Return provider is not selected or authorized.");
  const cadence = readEvidence<Cadence[]>(`${origin}/api/data-health?target=/data-health/return-ingestion/cadences`, Boolean(config.returnAccount && config.returnProvider && protectedApi), "Return account/provider evidence is not configured.");
  const strategy = readEvidence<StrategyCard>(`${origin}/api/research?target=/research/strategies/${encodeURIComponent(config.strategyId ?? "")}`, Boolean(config.strategyId && protectedApi), "Strategy research reference is not configured.");
  const experiment = readEvidence<Experiment>(`${origin}/api/research?target=/research/experiments/${encodeURIComponent(config.experimentId ?? "")}`, Boolean(config.experimentId && protectedApi), "Backtest experiment reference is not configured.");
  const promotion = readEvidence<Promotion>(`${origin}/api/research?target=/research/promotions/${encodeURIComponent(config.promotionDecisionId ?? "")}`, Boolean(config.promotionDecisionId && protectedApi), "Promotion decision reference is not configured.");
  const thesis = readEvidence<Thesis>(`${origin}/api/investments?target=/investments/theses/${encodeURIComponent(config.investmentThesisId ?? "")}`, Boolean(config.investmentThesisId && protectedApi), "Investment thesis reference is not configured.");
  const portfolio = readEvidence<InvestmentPortfolio>(`${origin}/api/investments?target=/investments/portfolios/${encodeURIComponent(config.investmentPortfolioId ?? "")}`, Boolean(config.investmentPortfolioId && protectedApi), "Investment portfolio reference is not configured.");
  const alerts = readEvidence<OperationalAlert[]>(`${origin}/api/alerts`, protectedApi, "Operator alert credentials are not configured.");
  const paperOrder = readEvidence<PaperOrder>(`${origin}/api/paper-oms?target=/paper-oms/orders/${encodeURIComponent(config.paperOrderIntentId ?? "")}`, Boolean(config.paperOrderIntentId && protectedApi), "Paper order evidence reference is not configured.");
  const reconciliation = readEvidence<Reconciliation>(`${origin}/api/paper-oms?target=/paper-oms/accounts/${encodeURIComponent(config.paperAccountId ?? "")}/reconciliation`, Boolean(config.paperAccountId && protectedApi), "Paper account evidence reference is not configured.");
  return <Dashboard command={await command} dataHealth={await dataHealth} cadence={await cadence} strategy={await strategy} experiment={await experiment} promotion={await promotion} thesis={await thesis} portfolio={await portfolio} alerts={await alerts} paperOrder={await paperOrder} reconciliation={await reconciliation} />;
}

function Dashboard({ command, dataHealth, cadence, strategy, experiment, promotion, thesis, portfolio, alerts, paperOrder, reconciliation }: { command: EvidenceResult<CommandCenterEvidence>; dataHealth: EvidenceResult<DataHealth>; cadence: EvidenceResult<Cadence[]>; strategy: EvidenceResult<StrategyCard>; experiment: EvidenceResult<Experiment>; promotion: EvidenceResult<Promotion>; thesis: EvidenceResult<Thesis>; portfolio: EvidenceResult<InvestmentPortfolio>; alerts: EvidenceResult<OperationalAlert[]>; paperOrder: EvidenceResult<PaperOrder>; reconciliation: EvidenceResult<Reconciliation> }) {
  const health = dataHealth.state === "AVAILABLE" ? dataHealth.value : undefined;
  const schedule = cadence.state === "AVAILABLE" ? cadence.value[0] : undefined;
  const strategyCard = strategy.state === "AVAILABLE" ? strategy.value : undefined;
  const backtest = experiment.state === "AVAILABLE" ? experiment.value : undefined;
  const investment = thesis.state === "AVAILABLE" ? thesis.value : undefined;
  const investmentPortfolio = portfolio.state === "AVAILABLE" ? portfolio.value : undefined;
  const order = paperOrder.state === "AVAILABLE" ? paperOrder.value : undefined;
  const account = reconciliation.state === "AVAILABLE" ? reconciliation.value : undefined;
  const commandEvidence = command.state === "AVAILABLE" ? command.value : undefined;
  const alertRows = alerts.state === "AVAILABLE" ? alerts.value : undefined;
  const latestValuation = investment?.valuations.at(-1); const company = investment?.company_research.at(-1); const latestPerformance = investmentPortfolio?.performance.at(-1);
  return <main id="main-content"><header><div><p className="eyebrow">PRIVATE READ-ONLY OPERATOR WORKSPACE</p><h1>Command Center</h1><p>Rendered evidence time: <time dateTime={new Date().toISOString()}>{utc(new Date().toISOString())}</time> UTC</p></div><span className="badge">LIVE TRADING: DISABLED</span></header>
    <nav aria-label="Operator workspaces"><a href="#data-sources">Data Sources</a><a href="#data-health">Data Health</a><a href="#instrument">Instruments</a><a href="#features">Features</a><a href="#strategy">Strategy Lab</a><a href="#backtest">Validation</a><a href="#scorecard">Scorecard</a><a href="#regime">Regime</a><a href="#portfolio">Portfolio</a><a href="#investment">Investment</a><a href="#news">News</a><a href="#paper-oms">Paper OMS</a><a href="#operations">Operations</a><a href="#audit">Audit</a></nav>
    <section className="cards" aria-label="Authoritative command summary"><article className="card"><p>Platform mode</p><strong>{commandEvidence?.platform_mode ?? stateText(command)}</strong><small>Backend command-center contract</small></article><article className="card"><p>Live trading</p><strong>DISABLED</strong><small>Build invariant; no execution authority</small></article><article className="card"><p>Critical alerts</p><strong>{commandEvidence?.states.find((item) => item.id === "critical-alerts")?.details.active_critical_alert_count?.toString() ?? "UNAVAILABLE"}</strong><small>Persisted alert authority</small></article><article className="card"><p>Data Health</p><strong>{health ? (health.healthy ? "HEALTHY" : "BLOCKING") : dataHealth.state}</strong><small>{health?.provider ?? (dataHealth.state === "EXTERNAL_BLOCKED" ? "Provider not configured" : stateText(dataHealth))}</small></article></section>
    <section className="grid">
      <article id="command"><h2>Command Center Evidence</h2>{commandEvidence ? <><dl><dt>Contract version</dt><dd>{commandEvidence.version}</dd><dt>Platform mode</dt><dd>{commandEvidence.platform_mode}</dd><dt>Live trading</dt><dd>{commandEvidence.live_trading_enabled ? "ENABLED" : "DISABLED"}</dd>{commandEvidence.states.map((item) => <><dt key={`${item.id}-label`}>{item.id}</dt><dd key={item.id}>{item.status}: {item.freshness}</dd></>)}</dl><EvidenceMeta source={commandEvidence.source} asOf={commandEvidence.as_of} version={commandEvidence.version} limitations={commandEvidence.limitations} /></> : <p className="empty-state">{stateText(command)}</p>}<span className="status">READ ONLY</span></article>
      <article id="data-sources"><h2>Data Sources / Providers</h2><p>Provider credentials and terms never enter the browser.</p><dl><dt>Provider</dt><dd>{health?.provider ?? "EXTERNAL_BLOCKED"}</dd><dt>Authorization / terms</dt><dd>{health ? "Configured record only; provider activation not asserted" : "EXTERNAL_BLOCKED"}</dd><dt>Health / freshness</dt><dd>{health ? `${health.healthy ? "HEALTHY" : "BLOCKING"}; checked ${utc(health.checked_at)}` : stateText(dataHealth)}</dd><dt>Checkpoint / dataset version</dt><dd>UNAVAILABLE</dd></dl><span className="status">{health ? "READ ONLY" : "EXTERNAL_BLOCKED"}</span></article>
      <article id="data-health"><h2>Data Health</h2><p>Blocking evidence is not bypassable from this console.</p><dl><dt>Assessment</dt><dd>{health ? `return-provider:${health.provider}` : "UNAVAILABLE"}</dd><dt>Severity / action</dt><dd>{health ? (health.healthy ? "HEALTHY / ALLOW" : "BLOCKING / REVIEW REQUIRED") : dataHealth.state}</dd><dt>Failures</dt><dd>{health?.consecutive_failures.toString() ?? "UNAVAILABLE"}</dd><dt>Reason</dt><dd>{health?.reason ?? "UNAVAILABLE"}</dd><dt>Cadence / last success</dt><dd>{schedule ? `${schedule.overdue ? "STALE" : schedule.due ? "DUE" : "CURRENT"}; ${utc(schedule.last_successful_at)}` : stateText(cadence)}</dd></dl>{health ? <EvidenceMeta source={`return-provider:${health.provider}`} asOf={health.checked_at} version="return-health-v1" limitations={["Dataset-level assessment is unavailable through this configured source."]} /> : null}<span className="status">READ ONLY</span></article>
      <article id="instrument"><h2>Instrument Workstation</h2><p>Point-in-time canonical mappings, lifecycle, sessions, and corporate actions require a configured instrument authority.</p><p className="empty-state">EXTERNAL_BLOCKED: no instrument lookup is configured. Ambiguous symbols are never guessed.</p><span className="status">EXTERNAL_BLOCKED / READ ONLY</span></article>
      <article id="features"><h2>Feature Explorer</h2><p>Inspect feature definition, semantic version, event/knowledge/computation times, quality, hash, and provenance before using it in research.</p><p className="empty-state">UNAVAILABLE: Feature Authority evidence is not wired to this deployment.</p><span className="status">UNAVAILABLE / READ ONLY</span></article>
      <article id="strategy"><h2>Strategy Laboratory</h2>{strategyCard ? <><dl><dt>Family / version</dt><dd>{strategyCard.family} / {strategyCard.strategy_version}</dd><dt>Hypothesis</dt><dd>{strategyCard.hypothesis}</dd><dt>Features / datasets</dt><dd>{strategyCard.feature_versions.join(", ")} / {strategyCard.required_datasets.join(", ")}</dd><dt>Regimes / failures</dt><dd>{strategyCard.expected_regimes.join(", ")} / {strategyCard.failure_conditions.join(", ")}</dd><dt>Evidence classification</dt><dd>{strategyCard.family.toLowerCase().includes("trend") ? "SYNTHETIC_ENGINEERING_EVIDENCE_ONLY" : "RESEARCH EVIDENCE ONLY"}</dd></dl><EvidenceMeta source="strategy-registry" asOf={strategyCard.created_at} version={strategyCard.strategy_version} limitations={strategyCard.limitations} /></> : <p className="empty-state">{stateText(strategy)}</p>}<span className="status">RESEARCH ONLY / READ ONLY</span></article>
      <article id="backtest"><h2>Backtest / Validation</h2>{backtest ? <><dl><dt>Strategy / dataset</dt><dd>{backtest.strategy_version} / {backtest.dataset_version}</dd><dt>Features / cost model</dt><dd>{backtest.feature_versions.join(", ")} / {backtest.cost_model_version}</dd><dt>Return</dt><dd>{String(backtest.report.total_return ?? "UNAVAILABLE")}</dd><dt>Independent accounting</dt><dd>{backtest.report.independent_bar_engine_reconciled === "1" ? "RECONCILED" : "UNAVAILABLE OR DIVERGENT"}</dd><dt>Walk-forward</dt><dd>{String(backtest.report.walk_forward_status ?? "UNAVAILABLE")}</dd><dt>Costs / capacity / latency</dt><dd>{String(backtest.report.pessimistic_cost_multiplier ?? "UNAVAILABLE")} / UNAVAILABLE / UNAVAILABLE</dd><dt>Promotion</dt><dd>{promotion.state === "AVAILABLE" ? `${promotion.value.status}: ${promotion.value.reasons.join(", ")}` : stateText(promotion)}</dd></dl><EvidenceMeta source="experiment-store" asOf={backtest.created_at} version={backtest.cost_model_version} limitations={["No aggregate score hides unavailable validation evidence."]} /></> : <p className="empty-state">{stateText(experiment)}</p>}<span className="status">HISTORICAL / RESEARCH ONLY</span></article>
      <UnconfiguredWorkspace id="scorecard" title="Strategy Scorecard" purpose="Performance, robustness, execution, risk, data quality, and complexity evidence remain separately inspectable; no unexplained AI score is shown." state="UNAVAILABLE" />
      <UnconfiguredWorkspace id="regime" title="Regime Workspace" purpose="Regime probabilities can reduce eligibility but cannot raise platform risk limits." state="UNAVAILABLE" />
      <UnconfiguredWorkspace id="portfolio" title="Portfolio Construction" purpose="Requested versus review weights, risk contributions, limits, and rejected allocations are review-only evidence." state="UNAVAILABLE" />
      <article id="investment"><h2>Investment Workspace</h2><p>NOT A REAL INVESTMENT RECOMMENDATION. Long-horizon research is separate from trading.</p>{investment ? <><dl><dt>Instrument / thesis</dt><dd>{investment.thesis.instrument_id} / {investment.thesis.statement}</dd><dt>Status / version</dt><dd>{investment.thesis.status} / {investment.thesis.version}</dd><dt>Catalysts / risks</dt><dd>{investment.thesis.catalysts.join(", ")} / {investment.thesis.risks.join(", ")}</dd><dt>Bear / base / bull</dt><dd>{company ? `${company.bear_case} / ${company.base_case} / ${company.bull_case}` : "UNAVAILABLE"}</dd><dt>Valuation</dt><dd>{latestValuation ? `${latestValuation.intrinsic_value_per_share}; ${latestValuation.model_version}` : "UNAVAILABLE"}</dd><dt>Latest review</dt><dd>{investment.reviews.at(-1)?.outcome ?? "UNAVAILABLE"}</dd></dl><EvidenceMeta source="investment-store" asOf={investment.as_of} version={investment.thesis.version} limitations={["Fixture valuation is not investment advice."]} /></> : <p className="empty-state">{stateText(thesis)}</p>}{investmentPortfolio ? <dl><dt>Portfolio / review state</dt><dd>{investmentPortfolio.portfolio_id} / {investmentPortfolio.assessment.approved ? "WITHIN LIMITS" : investmentPortfolio.assessment.reasons.join(", ")}</dd><dt>Value / NAV / return</dt><dd>{investmentPortfolio.assessment.total_value} / {latestPerformance ? `${latestPerformance.net_asset_value} / ${latestPerformance.cumulative_return}` : "UNAVAILABLE"}</dd><dt>Holdings provenance</dt><dd>{investmentPortfolio.holdings.map((item) => `${item.instrument_id}: ${item.source_reference}`).join("; ") || "EMPTY"}</dd><dt>Rebalance candidate</dt><dd>{investmentPortfolio.rebalance_decisions.at(-1)?.rationale ?? "EMPTY"}</dd></dl> : <p className="empty-state">{stateText(portfolio)}</p>}<span className="status">REVIEW ONLY / NO BUY OR SELL</span></article>
      <UnconfiguredWorkspace id="news" title="News / Event Intelligence" purpose="Sources, corrections, retractions, credibility, uncertainty, and replacement chains must be authoritative. News cannot create an order." />
      <article id="paper-oms"><h2>Paper OMS</h2><p>Paper lifecycle and reconciliation evidence only; this page cannot submit an order.</p>{order ? <><dl><dt>Intent / instrument</dt><dd>{order.intent_id} / {order.instrument_id}</dd><dt>Status / quantity / filled</dt><dd>{order.status} / {order.quantity} / {order.filled_quantity}</dd><dt>Partial fills</dt><dd>{order.fills.map((fill) => `${fill.external_fill_id}: ${fill.quantity} @ ${fill.price}`).join("; ") || "EMPTY"}</dd><dt>Lifecycle</dt><dd>{order.events.map((event) => `${event.event_type} @ ${utc(event.occurred_at)}`).join("; ")}</dd><dt>Reconciliation</dt><dd>{account ? `${account.complete ? "COMPLETE" : account.discrepancies.join(", ")}; ${account.source}; ${utc(account.occurred_at)}` : stateText(reconciliation)}</dd></dl><EvidenceMeta source="paper-oms" asOf={order.created_at} version="paper-oms-v1" limitations={["Paper-only evidence; no broker execution capability."]} /></> : <p className="empty-state">{stateText(paperOrder)}</p>}<span className="status">PAPER ONLY / READ ONLY</span></article>
      <article id="operations"><h2>Operations / SRE</h2><p>TARGET and MEASURED are distinct. This screen never claims achieved SLOs without an operational measurement.</p>{commandEvidence ? <dl>{commandEvidence.states.filter((item) => ["database-authority", "recovery-reconciliation", "kill-switch", "backup-restore", "ci-build"].map((item) => item).includes(item.id)).map((item) => <><dt key={`${item.id}-slo`}>{item.id}</dt><dd key={`${item.id}-value`}>{item.status}; {item.limitations.join(" ")}</dd></>)}</dl> : <p className="empty-state">{stateText(command)}</p>}<dl><dt>Active / critical incidents</dt><dd>{alertRows ? `${alertRows.length} / ${alertRows.filter((item) => item.severity === "CRITICAL").length}` : stateText(alerts)}</dd><dt>SLO targets</dt><dd>UNAVAILABLE: no target authority configured</dd><dt>Measured SLOs</dt><dd>UNAVAILABLE: no measurement authority configured</dd></dl><span className="status">READ ONLY / MEASUREMENT REQUIRED</span></article>
      <article id="audit"><h2>Audit</h2><p>Audit evidence is immutable and read-only: actor, action, domain object, version, timestamp, decision, reasons, and evidence IDs belong to protected backend records.</p><dl><dt>Alert evidence</dt><dd>{alertRows?.map((item) => `${item.alert_id}: ${item.severity} ${item.code} @ ${utc(item.created_at)}`).join("; ") || stateText(alerts)}</dd><dt>Mutation control</dt><dd>NO MUTATION ROUTE EXPOSED BY THIS DASHBOARD</dd></dl><span className="status">READ ONLY</span></article>
    </section><footer>Live trading is deliberately unavailable. This console has no live-execution, risk-override, kill-switch-bypass, or automatic strategy-activation control.</footer></main>;
}
