import { loadDashboardConfig } from "./dashboard-config";
import { ResearchLauncher } from "./research-launcher";
import { StrategyCreator } from "./strategy-creator";

const cards = [
  ["Portfolio", "$0.00", "No capital connected"], ["Gross exposure", "$0.00", "Paper-only"],
  ["Risk state", "CLEAR", "No active limit breach"], ["Data health", "FIXTURE", "Licensed feeds not configured"],
];
export const dynamic = "force-dynamic";

type DataHealth = { provider: string; healthy: boolean; checked_at: string; consecutive_failures: number; reason: string | null };
type Cadence = { account_id: string; provider: string; due: boolean; overdue: boolean; last_successful_at: string | null; approved_by: string };
type ThesisHistory = { thesis: { instrument_id: string; statement: string; status: string }; analytics: { revenue_growth: string; net_margin: string; free_cash_flow_margin: string; debt_to_equity: string; net_debt: string; unit: string }[]; reviews: { outcome: string; next_review_at: string }[]; company_research: { bull_case: string; base_case: string; bear_case: string; invalidation_conditions: string[]; replacement_candidates: string[] }[]; theme_discoveries: { theme: string; score: string; matched_phrases: string[]; rule_version: string }[]; review_schedule: { cadence_days: number; next_review_at: string } | null; scheduled_drift_history: { detected: boolean; breached_metrics: string[]; assessed_at: string }[] };
type InvestmentPortfolio = { portfolio_id: string; assessment: { total_value: string; approved: boolean; reasons: string[] }; holdings: { instrument_id: string; market_value: string }[]; rebalance_decisions: { rationale: string }[]; performance: { net_asset_value: string; cumulative_return: string }[] };
type OperationalAlert = { code: string; severity: string; resource: string; details: Record<string, string>; status: string };
type PaperOrderEvidence = { paper_only: boolean; instrument_id: string; account_id: string; side: string; quantity: string; limit_price: string; status: string; filled_quantity: string; average_fill_price: string | null; events: { event_type: string }[]; fills: { external_fill_id: string; quantity: string; price: string }[] };
type PaperReconciliation = { paper_only: boolean; complete: boolean; discrepancies: string[]; reconciled_account: { healthy: boolean; buying_power: string; positions: Record<string, { quantity: string }> } | null };
type RiskDecisionEvidence = { decisions: { decision: string; reasons: string[]; decided_at: string }[] };
type StrategyCard = { strategy_version: string; family: string; hypothesis: string; expected_regimes: string[]; failure_conditions: string[] };
type Experiment = { strategy_version: string; dataset_version: string; report: Record<string, string | number | null> };
type Promotion = { status: string; reasons: string[]; held_out_periods: number; held_out_total_return: string | null };

async function getDataHealth(): Promise<DataHealth | null> {
  const { returnProvider: provider, dashboardOrigin: origin } = loadDashboardConfig();
  if (!provider) return null;
  try {
    const response = await fetch(`${origin}/api/data-health?target=/data-health/return-providers/${encodeURIComponent(provider)}`, { cache: "no-store" });
    return response.ok ? await response.json() : null;
  } catch { return null; }
}
async function getCadence(): Promise<Cadence | null> {
  const { returnAccount: account, returnProvider: provider, dashboardOrigin: origin } = loadDashboardConfig();
  if (!account || !provider) return null;
  try { const response = await fetch(`${origin}/api/data-health?target=/data-health/return-ingestion/cadences`, { cache: "no-store" }); const rows: Cadence[] = response.ok ? await response.json() : []; return rows.find((row) => row.account_id === account && row.provider === provider) ?? null; } catch { return null; }
}
async function getInvestment(): Promise<ThesisHistory | null> {
  const { investmentThesisId, dashboardOrigin: origin } = loadDashboardConfig(); if (!investmentThesisId) return null;
  try { const response = await fetch(`${origin}/api/investments?target=/investments/theses/${encodeURIComponent(investmentThesisId)}`, { cache: "no-store" }); return response.ok ? await response.json() : null; } catch { return null; }
}
async function getInvestmentPortfolio(): Promise<InvestmentPortfolio | null> {
  const { investmentPortfolioId, dashboardOrigin: origin } = loadDashboardConfig(); if (!investmentPortfolioId) return null;
  try { const response = await fetch(`${origin}/api/investments?target=/investments/portfolios/${encodeURIComponent(investmentPortfolioId)}`, { cache: "no-store" }); return response.ok ? await response.json() : null; } catch { return null; }
}
async function getAlerts(): Promise<OperationalAlert[] | null> {
  const { dashboardOrigin: origin } = loadDashboardConfig();
  try { const response = await fetch(`${origin}/api/alerts`, { cache: "no-store" }); return response.ok ? await response.json() : null; } catch { return null; }
}
async function getPaperOrder(): Promise<PaperOrderEvidence | null> {
  const { paperOrderIntentId, dashboardOrigin: origin } = loadDashboardConfig(); if (!paperOrderIntentId) return null;
  try { const response = await fetch(`${origin}/api/paper-oms?target=/paper-oms/orders/${encodeURIComponent(paperOrderIntentId)}`, { cache: "no-store" }); return response.ok ? await response.json() : null; } catch { return null; }
}
async function getPaperReconciliation(): Promise<PaperReconciliation | null> {
  const { paperAccountId, dashboardOrigin: origin } = loadDashboardConfig(); if (!paperAccountId) return null;
  try { const response = await fetch(`${origin}/api/paper-oms?target=/paper-oms/accounts/${encodeURIComponent(paperAccountId)}/reconciliation`, { cache: "no-store" }); return response.ok ? await response.json() : null; } catch { return null; }
}
async function getRiskDecisions(): Promise<RiskDecisionEvidence | null> {
  const { paperOrderIntentId, dashboardOrigin: origin } = loadDashboardConfig(); if (!paperOrderIntentId) return null;
  try { const response = await fetch(`${origin}/api/risk?target=/risk/decisions/${encodeURIComponent(paperOrderIntentId)}`, { cache: "no-store" }); return response.ok ? await response.json() : null; } catch { return null; }
}
async function getResearch<T>(kind: "strategies" | "experiments" | "promotions", id: string | undefined): Promise<T | null> { const { dashboardOrigin: origin } = loadDashboardConfig(); if (!id) return null; try { const response = await fetch(`${origin}/api/research?target=/research/${kind}/${encodeURIComponent(id)}`, { cache: "no-store" }); return response.ok ? await response.json() : null; } catch { return null; } }
export default function Home() {
  const config = loadDashboardConfig(); return <Dashboard dataHealth={getDataHealth()} cadence={getCadence()} investment={getInvestment()} portfolio={getInvestmentPortfolio()} alerts={getAlerts()} paperOrder={getPaperOrder()} reconciliation={getPaperReconciliation()} riskDecisions={getRiskDecisions()} strategy={getResearch<StrategyCard>("strategies", config.strategyId)} experiment={getResearch<Experiment>("experiments", config.experimentId)} promotion={getResearch<Promotion>("promotions", config.promotionDecisionId)} />;
}

async function Dashboard({ dataHealth, cadence, investment, portfolio, alerts, paperOrder, reconciliation, riskDecisions, strategy, experiment, promotion }: { dataHealth: Promise<DataHealth | null>; cadence: Promise<Cadence | null>; investment: Promise<ThesisHistory | null>; portfolio: Promise<InvestmentPortfolio | null>; alerts: Promise<OperationalAlert[] | null>; paperOrder: Promise<PaperOrderEvidence | null>; reconciliation: Promise<PaperReconciliation | null>; riskDecisions: Promise<RiskDecisionEvidence | null>; strategy: Promise<StrategyCard | null>; experiment: Promise<Experiment | null>; promotion: Promise<Promotion | null> }) {
  const health = await dataHealth; const schedule = await cadence; const thesis = await investment; const investmentPortfolio = await portfolio; const activeAlerts = await alerts; const order = await paperOrder; const accountReconciliation = await reconciliation; const risk = await riskDecisions; const strategyCard = await strategy; const backtest = await experiment; const promotionDecision = await promotion; const latestRisk = risk?.decisions.at(-1); const analytics = thesis?.analytics.at(-1); const research = thesis?.company_research.at(-1); const theme = thesis?.theme_discoveries.at(-1); const scheduledDrift = thesis?.scheduled_drift_history.at(-1); const performance = investmentPortfolio?.performance.at(-1);
  const dataStatus = health ? (health.healthy ? "HEALTHY" : "DEGRADED") : "UNCONFIGURED";
  const dataNote = health ? `${health.provider}: ${health.consecutive_failures} consecutive failures` : "Return provider not configured";
  const dashboardConfig = loadDashboardConfig(); return <main><header><div><p className="eyebrow">PRIVATE OPERATOR WORKSPACE</p><h1>Command Center</h1></div><span className="badge">PAPER ONLY</span></header>
  <nav aria-label="Operator workspaces"><a href="#market">Market</a><a href="#instrument">Instrument</a><a href="#research">Strategy Lab</a><a href="#backtest">Backtests</a><a href="#risk">Risk</a><a href="#paper-oms">Paper OMS</a><a href="#data-health">Data Health</a><a href="#investment">Investments</a><a href="#audit">Audit</a></nav>
  <section className="cards" aria-label="Portfolio summary">{[...cards.slice(0, 3), ["Data health", dataStatus, dataNote]].map(([name,value,note])=><article className="card" key={name}><p>{name}</p><strong>{value}</strong><small>{note}</small></article>)}</section>
  <section className="grid">
    <article id="risk"><h2>Risk Center</h2><p>Persisted deterministic risk evidence is read-only; this screen cannot evaluate or override risk.</p>{latestRisk ? <dl><dt>Latest decision</dt><dd>{latestRisk.decision}</dd><dt>Reasons</dt><dd>{latestRisk.reasons.join(", ") || "None"}</dd><dt>Decided at</dt><dd>{latestRisk.decided_at}</dd></dl> : <p>No configured risk-decision evidence.</p>}<span className="status">READ ONLY</span></article>
    <article id="research"><h2>Strategy Laboratory</h2>{strategyCard ? <dl><dt>Version / family</dt><dd>{strategyCard.strategy_version} / {strategyCard.family}</dd><dt>Hypothesis</dt><dd>{strategyCard.hypothesis}</dd><dt>Expected regimes</dt><dd>{strategyCard.expected_regimes.join(", ")}</dd><dt>Failure conditions</dt><dd>{strategyCard.failure_conditions.join(", ")}</dd></dl> : <p>No configured strategy research evidence.</p>}<StrategyCreator /><span className="status">RESEARCH ONLY</span></article>
    <article id="backtest"><h2>Backtest Review</h2>{backtest ? <dl><dt>Strategy / dataset</dt><dd>{backtest.strategy_version} / {backtest.dataset_version}</dd><dt>Total return</dt><dd>{String(backtest.report.total_return ?? "Unavailable")}</dd><dt>Pessimistic-cost return</dt><dd>{backtest.report.pessimistic_cost_multiplier ? `${backtest.report.pessimistic_cost_multiplier}x: ${backtest.report.pessimistic_total_return ?? "Unavailable"}` : "Not recorded for this experiment"}</dd><dt>Independent accounting</dt><dd>{backtest.report.independent_bar_engine_reconciled === "1" ? "RECONCILED" : backtest.report.independent_bar_engine_reconciled === "0" ? `MISMATCH: ${String(backtest.report.independent_bar_engine_differences ?? "unspecified")}` : "Not recorded"}</dd><dt>Walk-forward evidence</dt><dd>{backtest.report.walk_forward_status === "EXECUTED" ? `${backtest.report.walk_forward_splits} non-overlapping splits; ${backtest.report.walk_forward_held_out_periods} held-out periods; return ${String(backtest.report.walk_forward_total_return)}` : String(backtest.report.walk_forward_status ?? "Not recorded")}</dd><dt>Promotion</dt><dd>{promotionDecision?.status ?? "No configured promotion decision"}</dd><dt>Promotion reasons</dt><dd>{promotionDecision?.reasons.join(", ") ?? "Unavailable"}</dd><dt>Held-out periods / return</dt><dd>{promotionDecision ? `${promotionDecision.held_out_periods} / ${promotionDecision.held_out_total_return ?? "Unavailable"}` : "Unavailable"}</dd></dl> : <p>No configured backtest evidence.</p>}<ResearchLauncher strategyId={dashboardConfig.strategyId} /><span className="status">HISTORICAL ONLY / RESEARCH ONLY</span></article>
    <article id="market"><h2>Market Intelligence</h2><p>Fixture-only market data is provenance-checked, point-in-time gated, and visibly marked until lawful provider data is configured.</p><span className="status">FIXTURE DATA</span></article>
    <article id="data-health"><h2>Return Data Health</h2><p>Historical portfolio-risk evidence is read-only here. Provider imports remain separately authorized and cannot submit orders.</p><dl><dt>Provider</dt><dd>{health?.provider ?? "Not configured"}</dd><dt>State</dt><dd>{dataStatus}</dd><dt>Last check</dt><dd>{health?.checked_at ?? "No durable provider health record"}</dd><dt>Failure reason</dt><dd>{health?.reason ?? "None"}</dd><dt>Cadence</dt><dd>{schedule ? (schedule.overdue ? "OVERDUE" : schedule.due ? "DUE" : "CURRENT") : "No configured cadence"}</dd><dt>Last successful import</dt><dd>{schedule?.last_successful_at ?? "No successful import recorded"}</dd></dl><span className="status">READ ONLY</span></article>
    <article id="instrument"><h2>Instrument Workstation</h2><p>Canonical, venue-qualified identifiers prevent ambiguous symbol routing. No broker instrument is connected.</p><span className="status">LOCAL CATALOG</span></article>
    <article id="paper-oms"><h2>Paper OMS Evidence</h2><p>Persisted paper-order lifecycle and reconciliation evidence only. No order action is available here.</p>{order ? <dl><dt>Instrument / side</dt><dd>{order.instrument_id} / {order.side}</dd><dt>Status</dt><dd>{order.status}</dd><dt>Quantity / filled</dt><dd>{order.quantity} / {order.filled_quantity}</dd><dt>Limit / average fill</dt><dd>{order.limit_price} / {order.average_fill_price ?? "No fill"}</dd><dt>Lifecycle events</dt><dd>{order.events.map((item) => item.event_type).join(", ")}</dd><dt>Recorded fills</dt><dd>{order.fills.map((item) => `${item.external_fill_id}: ${item.quantity} @ ${item.price}`).join("; ") || "None"}</dd></dl> : <p>No configured paper order evidence.</p>}{accountReconciliation ? <dl><dt>Reconciliation</dt><dd>{accountReconciliation.complete ? "COMPLETE" : accountReconciliation.discrepancies.join(", ")}</dd><dt>Account health</dt><dd>{accountReconciliation.reconciled_account?.healthy ? "HEALTHY" : "No complete account evidence"}</dd><dt>Buying power</dt><dd>{accountReconciliation.reconciled_account?.buying_power ?? "Unavailable"}</dd><dt>Positions</dt><dd>{accountReconciliation.reconciled_account ? Object.entries(accountReconciliation.reconciled_account.positions).map(([instrument, position]) => `${instrument}: ${position.quantity}`).join("; ") || "None" : "Unavailable"}</dd></dl> : <p>No configured reconciliation evidence.</p>}<span className="status">PAPER ONLY / READ ONLY</span></article>
    <article id="investment"><h2>Investment Workspace</h2><p>Long-horizon research is separate from paper trading and remains read-only.</p>{thesis ? <dl><dt>Instrument</dt><dd>{thesis.thesis.instrument_id}</dd><dt>Thesis</dt><dd>{thesis.thesis.statement}</dd><dt>Revenue growth</dt><dd>{analytics?.revenue_growth ?? "Unavailable"}</dd><dt>Net margin</dt><dd>{analytics?.net_margin ?? "Unavailable"}</dd><dt>Debt / equity</dt><dd>{analytics?.debt_to_equity ?? "Unavailable"}</dd><dt>Latest review</dt><dd>{thesis.reviews.at(-1)?.outcome ?? "No review recorded"}</dd><dt>Next scheduled review</dt><dd>{thesis.review_schedule?.next_review_at ?? "No approved schedule"}</dd><dt>Scheduled drift</dt><dd>{scheduledDrift ? (scheduledDrift.detected ? `DETECTED: ${scheduledDrift.breached_metrics.join(", ")}` : "No drift detected") : "No scheduled assessment"}</dd><dt>Discovered theme</dt><dd>{theme ? `${theme.theme} (${theme.score}; ${theme.matched_phrases.join(", ")}; ${theme.rule_version})` : "No rule-bound theme discovery"}</dd><dt>Bull / base / bear</dt><dd>{research ? `${research.bull_case} / ${research.base_case} / ${research.bear_case}` : "No company case recorded"}</dd><dt>Invalidation</dt><dd>{research?.invalidation_conditions.join("; ") ?? "Unavailable"}</dd><dt>Replacement candidates</dt><dd>{research?.replacement_candidates.join(", ") ?? "None recorded"}</dd></dl> : <p>No investment thesis configured.</p>}{investmentPortfolio ? <dl><dt>Investment portfolio</dt><dd>{investmentPortfolio.portfolio_id}</dd><dt>Policy state</dt><dd>{investmentPortfolio.assessment.approved ? "WITHIN LIMITS" : investmentPortfolio.assessment.reasons.join(", ")}</dd><dt>Value</dt><dd>{investmentPortfolio.assessment.total_value}</dd><dt>Latest NAV / return</dt><dd>{performance ? `${performance.net_asset_value} / ${performance.cumulative_return}` : "No performance snapshot"}</dd><dt>Holdings</dt><dd>{investmentPortfolio.holdings.map((holding) => `${holding.instrument_id}: ${holding.market_value}`).join("; ") || "None"}</dd><dt>Latest rebalance</dt><dd>{investmentPortfolio.rebalance_decisions.at(-1)?.rationale ?? "None"}</dd></dl> : <p>No investment portfolio configured.</p>}<span className="status">READ ONLY</span></article>
    <article id="audit"><h2>Audit Center</h2><p>Append-only local events, protected API access, and decision evidence support operator review and incident investigation.</p><dl><dt>Active alerts</dt><dd>{activeAlerts ? `${activeAlerts.length}` : "Alert service unavailable"}</dd><dt>Latest alert</dt><dd>{activeAlerts?.at(-1) ? `${activeAlerts.at(-1)?.severity}: ${activeAlerts.at(-1)?.code} (${activeAlerts.at(-1)?.resource})` : "None"}</dd></dl><span className="status">READ ONLY</span></article>
    <article><h2>System Health</h2><p>API health, audit events, data quality, and job telemetry will surface here.</p><span className="status">LOCAL / HEALTHY</span></article>
  </section>
  <footer>Live trading is deliberately unavailable. Broker credentials and real orders are not supported.</footer></main>;
}
