"use client";

import { FormEvent, useState } from "react";

export function ResearchLauncher({ strategyId }: { strategyId?: string }) {
  const [datasetVersion, setDatasetVersion] = useState("fixture-v1"); const [closes, setCloses] = useState(Array.from({ length: 40 }, (_, index) => String(100 + index)).join(",")); const [fastWindow, setFastWindow] = useState("2"); const [slowWindow, setSlowWindow] = useState("3"); const [pessimisticCostMultiplier, setPessimisticCostMultiplier] = useState("2"); const [idempotencyKey, setIdempotencyKey] = useState("dashboard-backtest-1"); const [result, setResult] = useState<string>();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!strategyId) return; setResult("Launching historical research and held-out validation…"); const response = await fetch("/api/research", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "launch_backtest", strategy_id: strategyId, dataset_version: datasetVersion, parameters: { fast_window: Number(fastWindow), slow_window: Number(slowWindow) }, closes: closes.split(",").map((item) => item.trim()), pessimistic_cost_multiplier: pessimisticCostMultiplier, walk_forward_train_size: 10, walk_forward_validation_size: 4, walk_forward_test_size: 5, walk_forward_step: 5, walk_forward_purge: 1, walk_forward_embargo: 1, idempotency_key: idempotencyKey }) }); const body: unknown = await response.json(); const detail = body && typeof body === "object" && "detail" in body && typeof body.detail === "string" ? body.detail : "Invalid research backtest launch."; setResult(response.ok && body && typeof body === "object" && "report" in body && "experiment_id" in body ? `Completed experiment ${body.experiment_id}; base ${(body.report as Record<string, string>).total_return}; ${(body.report as Record<string, string>).pessimistic_cost_multiplier}x-cost ${(body.report as Record<string, string>).pessimistic_total_return}; held-out ${(body.report as Record<string, string>).walk_forward_status} (${(body.report as Record<string, string>).walk_forward_held_out_periods} periods); independent engine ${(body.report as Record<string, string>).independent_bar_engine_reconciled === "1" ? "reconciled" : "mismatch"}.` : detail); }
  return <form onSubmit={submit}><p>Runs a fixed, non-overlapping purged/embargoed walk-forward protocol (10/4/5, step 5, purge 1, embargo 1) and an independent accounting check. This remains historical research only.</p><label>Dataset version<input aria-label="Dataset version" value={datasetVersion} onChange={(event) => setDatasetVersion(event.target.value)} required /></label><label>Closes<input aria-label="Closes" value={closes} onChange={(event) => setCloses(event.target.value)} required /></label><label>Fast window<input aria-label="Fast window" value={fastWindow} onChange={(event) => setFastWindow(event.target.value)} required /></label><label>Slow window<input aria-label="Slow window" value={slowWindow} onChange={(event) => setSlowWindow(event.target.value)} required /></label><label>Pessimistic cost multiplier<input aria-label="Pessimistic cost multiplier" type="number" min="1" step="0.1" value={pessimisticCostMultiplier} onChange={(event) => setPessimisticCostMultiplier(event.target.value)} required /></label><label>Idempotency key<input aria-label="Backtest idempotency key" value={idempotencyKey} onChange={(event) => setIdempotencyKey(event.target.value)} required /></label><button type="submit" disabled={!strategyId}>Launch historical backtest</button><p aria-live="polite">{strategyId ? result ?? "No launch submitted." : "Strategy ID is not configured."}</p></form>;
}
