"""Normalized PostgreSQL DDL used by the forward-only Alembic migration.

SQLite remains a deliberately lightweight adapter for deterministic tests.  This
schema is the production transactional target: money and quantities are NUMERIC,
identity/version/provenance fields are relational, and JSONB is only retained
for genuinely variable payloads.
"""

INITIAL_SCHEMA_SQL: tuple[str, ...] = (
    "CREATE EXTENSION IF NOT EXISTS pgcrypto",
    """CREATE TABLE exchanges (exchange_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), mic TEXT NOT NULL UNIQUE, name TEXT NOT NULL, timezone TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now())""",
    """CREATE TABLE trading_calendars (calendar_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), exchange_id UUID NOT NULL REFERENCES exchanges(exchange_id), version TEXT NOT NULL, session_rules JSONB NOT NULL, effective_at TIMESTAMPTZ NOT NULL, ingested_at TIMESTAMPTZ NOT NULL, UNIQUE(exchange_id, version))""",
    """CREATE TABLE instruments (instrument_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), exchange_id UUID REFERENCES exchanges(exchange_id), canonical_symbol TEXT NOT NULL, asset_class TEXT NOT NULL, currency CHAR(3) NOT NULL, tick_size NUMERIC(30,12) NOT NULL CHECK(tick_size > 0), lot_size NUMERIC(30,12) NOT NULL CHECK(lot_size > 0), active_from TIMESTAMPTZ NOT NULL, delisted_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(delisted_at IS NULL OR delisted_at >= active_from), UNIQUE(exchange_id, canonical_symbol, active_from))""",
    """CREATE TABLE instrument_identifiers (identifier_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), instrument_id UUID NOT NULL REFERENCES instruments(instrument_id), namespace TEXT NOT NULL, value TEXT NOT NULL, valid_from TIMESTAMPTZ NOT NULL, valid_to TIMESTAMPTZ, source TEXT NOT NULL, ingested_at TIMESTAMPTZ NOT NULL, CHECK(valid_to IS NULL OR valid_to > valid_from), UNIQUE(namespace, value, valid_from))""",
    "CREATE INDEX instrument_identifiers_lookup_idx ON instrument_identifiers(namespace, value, valid_from DESC)",
    """CREATE TABLE datasets (dataset_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL UNIQUE, provider TEXT NOT NULL, terms_version TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now())""",
    """CREATE TABLE dataset_versions (dataset_version_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), dataset_id UUID NOT NULL REFERENCES datasets(dataset_id), version TEXT NOT NULL, content_hash CHAR(64) NOT NULL UNIQUE, valid_from TIMESTAMPTZ, valid_to TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL, UNIQUE(dataset_id, version))""",
    """CREATE TABLE market_data_provenance (provenance_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), dataset_version_id UUID NOT NULL REFERENCES dataset_versions(dataset_version_id), provider TEXT NOT NULL, source_identifier TEXT NOT NULL, revision INTEGER NOT NULL CHECK(revision >= 0), occurred_at TIMESTAMPTZ NOT NULL, available_at TIMESTAMPTZ NOT NULL, ingested_at TIMESTAMPTZ NOT NULL, quality_score NUMERIC(8,6) NOT NULL CHECK(quality_score BETWEEN 0 AND 1), UNIQUE(dataset_version_id, provider, source_identifier, revision))""",
    "CREATE INDEX market_data_provenance_asof_idx ON market_data_provenance(dataset_version_id, occurred_at, available_at, ingested_at)",
    """CREATE TABLE market_bars (bar_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), provenance_id UUID NOT NULL REFERENCES market_data_provenance(provenance_id), instrument_id UUID NOT NULL REFERENCES instruments(instrument_id), occurred_at TIMESTAMPTZ NOT NULL, open NUMERIC(30,12) NOT NULL CHECK(open > 0), high NUMERIC(30,12) NOT NULL CHECK(high > 0), low NUMERIC(30,12) NOT NULL CHECK(low > 0), close NUMERIC(30,12) NOT NULL CHECK(close > 0), volume NUMERIC(30,12) NOT NULL CHECK(volume >= 0), CHECK(high >= low AND high >= open AND high >= close AND low <= open AND low <= close), UNIQUE(provenance_id, instrument_id, occurred_at))""",
    "CREATE INDEX market_bars_instrument_time_idx ON market_bars(instrument_id, occurred_at DESC)",
    """CREATE TABLE corporate_actions (action_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), instrument_id UUID NOT NULL REFERENCES instruments(instrument_id), provenance_id UUID NOT NULL REFERENCES market_data_provenance(provenance_id), action_type TEXT NOT NULL CHECK(action_type IN ('SPLIT','DIVIDEND','SYMBOL_CHANGE','DELISTING')), effective_at TIMESTAMPTZ NOT NULL, announced_at TIMESTAMPTZ NOT NULL, payload JSONB NOT NULL, UNIQUE(provenance_id, action_type, effective_at))""",
    """CREATE TABLE fundamental_facts (fact_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), instrument_id UUID NOT NULL REFERENCES instruments(instrument_id), provenance_id UUID NOT NULL REFERENCES market_data_provenance(provenance_id), statement_type TEXT NOT NULL, metric TEXT NOT NULL, period_end DATE NOT NULL, filed_at TIMESTAMPTZ NOT NULL, value NUMERIC(38,12) NOT NULL, currency CHAR(3), UNIQUE(provenance_id, metric, period_end))""",
    "CREATE INDEX fundamental_facts_asof_idx ON fundamental_facts(instrument_id, metric, filed_at DESC)",
    """CREATE TABLE macro_observations (observation_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), provenance_id UUID NOT NULL REFERENCES market_data_provenance(provenance_id), series_code TEXT NOT NULL, observation_date DATE NOT NULL, released_at TIMESTAMPTZ NOT NULL, actual NUMERIC(38,12), expected NUMERIC(38,12), prior NUMERIC(38,12), UNIQUE(provenance_id, series_code, observation_date))""",
    "CREATE INDEX macro_observations_asof_idx ON macro_observations(series_code, released_at DESC)",
    """CREATE TABLE news_events (news_event_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), provenance_id UUID NOT NULL REFERENCES market_data_provenance(provenance_id), canonical_entity TEXT, published_at TIMESTAMPTZ NOT NULL, url TEXT NOT NULL, source_reliability NUMERIC(8,6), payload JSONB NOT NULL, UNIQUE(provenance_id, url))""",
    """CREATE TABLE feature_definitions (feature_definition_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, version TEXT NOT NULL, owner TEXT NOT NULL, frequency TEXT NOT NULL, timing_semantics TEXT NOT NULL, definition JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL, UNIQUE(name, version))""",
    """CREATE TABLE feature_values (feature_value_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), feature_definition_id UUID NOT NULL REFERENCES feature_definitions(feature_definition_id), instrument_id UUID REFERENCES instruments(instrument_id), dataset_version_id UUID NOT NULL REFERENCES dataset_versions(dataset_version_id), occurred_at TIMESTAMPTZ NOT NULL, available_at TIMESTAMPTZ NOT NULL, value NUMERIC(38,12), provenance_id UUID REFERENCES market_data_provenance(provenance_id), UNIQUE(feature_definition_id, instrument_id, dataset_version_id, occurred_at, available_at))""",
    "CREATE INDEX feature_values_asof_idx ON feature_values(feature_definition_id, instrument_id, occurred_at, available_at DESC)",
    """CREATE TABLE strategy_definitions (strategy_id UUID PRIMARY KEY, family TEXT NOT NULL, hypothesis TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL)""",
    """CREATE TABLE strategy_versions (strategy_version_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), strategy_id UUID NOT NULL REFERENCES strategy_definitions(strategy_id), version TEXT NOT NULL, feature_manifest JSONB NOT NULL, cost_model_version TEXT NOT NULL, capacity_model_version TEXT NOT NULL, contract JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL, UNIQUE(strategy_id, version))""",
    """CREATE TABLE research_experiments (experiment_id UUID PRIMARY KEY, strategy_version_id UUID NOT NULL REFERENCES strategy_versions(strategy_version_id), dataset_version_id UUID NOT NULL REFERENCES dataset_versions(dataset_version_id), parameters JSONB NOT NULL, report JSONB NOT NULL, content_hash CHAR(64) NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL)""",
    "CREATE INDEX research_experiments_strategy_dataset_idx ON research_experiments(strategy_version_id, dataset_version_id, created_at DESC)",
    """CREATE TABLE walk_forward_evidence (walk_forward_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), experiment_id UUID NOT NULL REFERENCES research_experiments(experiment_id), split_index INTEGER NOT NULL CHECK(split_index >= 0), train_start TIMESTAMPTZ NOT NULL, train_end TIMESTAMPTZ NOT NULL, validation_start TIMESTAMPTZ NOT NULL, validation_end TIMESTAMPTZ NOT NULL, test_start TIMESTAMPTZ NOT NULL, test_end TIMESTAMPTZ NOT NULL, report JSONB NOT NULL, content_hash CHAR(64) NOT NULL UNIQUE, CHECK(train_start < train_end AND train_end <= validation_start AND validation_start < validation_end AND validation_end <= test_start AND test_start < test_end), UNIQUE(experiment_id, split_index))""",
    """CREATE TABLE golden_execution_artifacts (golden_artifact_id UUID PRIMARY KEY, strategy_version_id UUID NOT NULL REFERENCES strategy_versions(strategy_version_id), dataset_version_id UUID NOT NULL REFERENCES dataset_versions(dataset_version_id), scenario_version TEXT NOT NULL, reconciled BOOLEAN NOT NULL, content_hash CHAR(64) NOT NULL UNIQUE, report JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL)""",
    """CREATE TABLE quant_validation_artifacts (quant_artifact_id UUID PRIMARY KEY, artifact_type TEXT NOT NULL CHECK(artifact_type IN ('capacity','slippage','latency','bootstrap','monte_carlo','stress','parameter_stability','multiple_testing','data_quality','scorecard','execution_realism')), strategy_version_id UUID NOT NULL REFERENCES strategy_versions(strategy_version_id), dataset_version_id UUID NOT NULL REFERENCES dataset_versions(dataset_version_id), artifact_version TEXT NOT NULL, content_hash CHAR(64) NOT NULL UNIQUE, passed BOOLEAN, evaluated_at TIMESTAMPTZ NOT NULL, payload JSONB NOT NULL, UNIQUE(strategy_version_id, dataset_version_id, artifact_type, artifact_version, content_hash))""",
    "CREATE INDEX quant_validation_lookup_idx ON quant_validation_artifacts(strategy_version_id, dataset_version_id, artifact_type, evaluated_at DESC)",
    """CREATE TABLE validation_packages (package_id UUID PRIMARY KEY, strategy_version_id UUID NOT NULL REFERENCES strategy_versions(strategy_version_id), dataset_version_id UUID NOT NULL REFERENCES dataset_versions(dataset_version_id), cost_model_version TEXT NOT NULL, content_hash CHAR(64) NOT NULL UNIQUE, status TEXT NOT NULL CHECK(status IN ('BLOCKED','REVIEW_REQUIRED_OR_BLOCKED')), created_at TIMESTAMPTZ NOT NULL, limitations JSONB NOT NULL)""",
    """CREATE TABLE validation_package_artifacts (package_id UUID NOT NULL REFERENCES validation_packages(package_id), quant_artifact_id UUID NOT NULL REFERENCES quant_validation_artifacts(quant_artifact_id), evidence_type TEXT NOT NULL, PRIMARY KEY(package_id, evidence_type), UNIQUE(package_id, quant_artifact_id))""",
    """CREATE TABLE strategy_promotion_decisions (decision_id UUID PRIMARY KEY, package_id UUID NOT NULL REFERENCES validation_packages(package_id), strategy_version_id UUID NOT NULL REFERENCES strategy_versions(strategy_version_id), status TEXT NOT NULL CHECK(status IN ('BLOCKED','REVIEW_REQUIRED')), reasons JSONB NOT NULL, held_out_periods INTEGER NOT NULL CHECK(held_out_periods >= 0), held_out_total_return NUMERIC(30,12), decided_at TIMESTAMPTZ NOT NULL, UNIQUE(package_id, decided_at))""",
    """CREATE TABLE model_registry (model_id UUID PRIMARY KEY, model_version TEXT NOT NULL, task TEXT NOT NULL, feature_manifest JSONB NOT NULL, dataset_version_id UUID NOT NULL REFERENCES dataset_versions(dataset_version_id), artifact_hash CHAR(64) NOT NULL, status TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, UNIQUE(model_id, model_version))""",
    """CREATE TABLE model_predictions (prediction_id UUID PRIMARY KEY, model_id UUID NOT NULL REFERENCES model_registry(model_id), model_version TEXT NOT NULL, instrument_id UUID REFERENCES instruments(instrument_id), predicted_at TIMESTAMPTZ NOT NULL, expires_at TIMESTAMPTZ NOT NULL, value NUMERIC(30,12) NOT NULL, uncertainty NUMERIC(30,12), explanation JSONB NOT NULL, CHECK(expires_at > predicted_at))""",
    """CREATE TABLE signals (signal_id UUID PRIMARY KEY, strategy_version_id UUID NOT NULL REFERENCES strategy_versions(strategy_version_id), instrument_id UUID NOT NULL REFERENCES instruments(instrument_id), status TEXT NOT NULL, proposed_at TIMESTAMPTZ NOT NULL, expires_at TIMESTAMPTZ NOT NULL, payload JSONB NOT NULL, CHECK(expires_at > proposed_at))""",
    """CREATE TABLE signal_events (signal_event_id UUID PRIMARY KEY, signal_id UUID NOT NULL REFERENCES signals(signal_id), event_type TEXT NOT NULL, occurred_at TIMESTAMPTZ NOT NULL, payload JSONB NOT NULL)""",
    """CREATE TABLE risk_policies (risk_policy_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL)""",
    """CREATE TABLE risk_policy_versions (risk_policy_version_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), risk_policy_id UUID NOT NULL REFERENCES risk_policies(risk_policy_id), version TEXT NOT NULL, limits JSONB NOT NULL, content_hash CHAR(64) NOT NULL UNIQUE, effective_at TIMESTAMPTZ NOT NULL, UNIQUE(risk_policy_id, version))""",
    """CREATE TABLE accounts (account_id TEXT PRIMARY KEY, account_type TEXT NOT NULL CHECK(account_type IN ('PAPER','INVESTMENT')), currency CHAR(3) NOT NULL, created_at TIMESTAMPTZ NOT NULL)""",
    """CREATE TABLE risk_decisions (risk_decision_id UUID PRIMARY KEY, intent_id UUID NOT NULL, risk_policy_version_id UUID NOT NULL REFERENCES risk_policy_versions(risk_policy_version_id), approved BOOLEAN NOT NULL, reasons JSONB NOT NULL, decided_at TIMESTAMPTZ NOT NULL, UNIQUE(intent_id))""",
    """CREATE TABLE risk_reservations (reservation_id UUID PRIMARY KEY, account_id TEXT NOT NULL REFERENCES accounts(account_id), intent_id UUID NOT NULL UNIQUE, business_date DATE NOT NULL, notional NUMERIC(30,12) NOT NULL CHECK(notional >= 0), created_at TIMESTAMPTZ NOT NULL, UNIQUE(account_id, intent_id))""",
    "CREATE INDEX risk_reservations_daily_idx ON risk_reservations(account_id, business_date)",
    """CREATE TABLE portfolio_positions (position_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), account_id TEXT NOT NULL REFERENCES accounts(account_id), instrument_id UUID NOT NULL REFERENCES instruments(instrument_id), as_of TIMESTAMPTZ NOT NULL, quantity NUMERIC(30,12) NOT NULL, average_cost NUMERIC(30,12) NOT NULL, UNIQUE(account_id, instrument_id, as_of))""",
    """CREATE TABLE paper_order_intents (intent_id UUID PRIMARY KEY, signal_id UUID NOT NULL REFERENCES signals(signal_id), account_id TEXT NOT NULL REFERENCES accounts(account_id), instrument_id UUID NOT NULL REFERENCES instruments(instrument_id), side TEXT NOT NULL CHECK(side IN ('BUY','SELL')), quantity NUMERIC(30,12) NOT NULL CHECK(quantity > 0), limit_price NUMERIC(30,12) NOT NULL CHECK(limit_price > 0), status TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL)""",
    """CREATE TABLE oms_events (oms_event_id UUID PRIMARY KEY, intent_id UUID NOT NULL REFERENCES paper_order_intents(intent_id), event_type TEXT NOT NULL, occurred_at TIMESTAMPTZ NOT NULL, payload JSONB NOT NULL)""",
    "CREATE INDEX oms_events_intent_idx ON oms_events(intent_id, occurred_at)",
    """CREATE TABLE fills (fill_id UUID PRIMARY KEY, external_fill_id TEXT NOT NULL UNIQUE, intent_id UUID NOT NULL REFERENCES paper_order_intents(intent_id), occurred_at TIMESTAMPTZ NOT NULL, quantity NUMERIC(30,12) NOT NULL CHECK(quantity > 0), price NUMERIC(30,12) NOT NULL CHECK(price > 0))""",
    """CREATE TABLE broker_event_cursors (account_id TEXT NOT NULL REFERENCES accounts(account_id), source TEXT NOT NULL, cursor TEXT NOT NULL, advanced_at TIMESTAMPTZ NOT NULL, PRIMARY KEY(account_id, source))""",
    """CREATE TABLE reconciliations (reconciliation_id UUID PRIMARY KEY, account_id TEXT NOT NULL REFERENCES accounts(account_id), source TEXT NOT NULL, occurred_at TIMESTAMPTZ NOT NULL, complete BOOLEAN NOT NULL, discrepancies JSONB NOT NULL)""",
    """CREATE TABLE operational_alerts (alert_id UUID PRIMARY KEY, alert_type TEXT NOT NULL, severity TEXT NOT NULL, status TEXT NOT NULL, opened_at TIMESTAMPTZ NOT NULL, acknowledged_at TIMESTAMPTZ, payload JSONB NOT NULL)""",
    """CREATE TABLE investment_theses (thesis_id UUID PRIMARY KEY, instrument_id UUID NOT NULL REFERENCES instruments(instrument_id), version TEXT NOT NULL, status TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, UNIQUE(instrument_id, version))""",
    """CREATE TABLE investment_evidence (investment_evidence_id UUID PRIMARY KEY, thesis_id UUID NOT NULL REFERENCES investment_theses(thesis_id), provenance_id UUID REFERENCES market_data_provenance(provenance_id), occurred_at TIMESTAMPTZ NOT NULL, payload JSONB NOT NULL)""",
    """CREATE TABLE investment_reviews (review_id UUID PRIMARY KEY, thesis_id UUID NOT NULL REFERENCES investment_theses(thesis_id), reviewer TEXT NOT NULL, status TEXT NOT NULL, reviewed_at TIMESTAMPTZ NOT NULL, payload JSONB NOT NULL)""",
    """CREATE TABLE agent_research_workflows (workflow_id UUID PRIMARY KEY, strategy_version_id UUID REFERENCES strategy_versions(strategy_version_id), status TEXT NOT NULL, prompt_version TEXT NOT NULL, model_version TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL)""",
    """CREATE TABLE agent_research_outputs (output_id UUID PRIMARY KEY, workflow_id UUID NOT NULL REFERENCES agent_research_workflows(workflow_id), role TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, payload JSONB NOT NULL)""",
    """CREATE TABLE agent_research_reviews (agent_review_id UUID PRIMARY KEY, workflow_id UUID NOT NULL REFERENCES agent_research_workflows(workflow_id), reviewer TEXT NOT NULL, decision TEXT NOT NULL, reviewed_at TIMESTAMPTZ NOT NULL, notes TEXT NOT NULL)""",
    """CREATE TABLE audit_events (audit_event_id UUID PRIMARY KEY, actor TEXT NOT NULL, event_type TEXT NOT NULL, occurred_at TIMESTAMPTZ NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, payload JSONB NOT NULL, content_hash CHAR(64) NOT NULL UNIQUE)""",
    """CREATE OR REPLACE FUNCTION prevent_immutable_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'immutable evidence cannot be updated or deleted'; END; $$""",
)

IMMUTABLE_TABLES: tuple[str, ...] = (
    "market_data_provenance", "corporate_actions", "fundamental_facts", "macro_observations", "news_events",
    "feature_definitions", "research_experiments", "walk_forward_evidence", "golden_execution_artifacts",
    "quant_validation_artifacts", "validation_packages", "validation_package_artifacts",
    "strategy_promotion_decisions", "risk_decisions",
    "oms_events", "fills", "reconciliations", "audit_events",
)


def immutable_trigger_sql(table: str) -> str:
    return f"CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION prevent_immutable_mutation()"


def drop_schema_sql() -> tuple[str, ...]:
    """Downgrade policy: schema-only environments may be reset, never production."""
    tables = (
        "feature_materializations", "feature_definition_versions", "audit_events", "agent_research_reviews", "agent_research_outputs", "agent_research_workflows", "investment_reviews", "investment_evidence", "investment_theses", "operational_alerts", "reconciliations", "broker_event_cursors", "fills", "oms_events", "paper_order_intents", "portfolio_positions", "risk_reservations", "risk_decisions", "accounts", "risk_policy_versions", "risk_policies", "signal_events", "signals", "model_predictions", "model_registry", "strategy_promotion_decisions", "validation_package_artifacts", "validation_packages", "quant_validation_artifacts", "golden_execution_artifacts", "walk_forward_evidence", "research_experiments", "strategy_versions", "strategy_definitions", "feature_values", "feature_definitions", "news_events", "macro_observations", "fundamental_facts", "corporate_actions", "market_bars", "market_data_provenance", "dataset_versions", "datasets", "instrument_identifiers", "instruments", "trading_calendars", "exchanges",
    )
    return tuple(f"DROP TABLE IF EXISTS {table} CASCADE" for table in tables) + ("DROP FUNCTION IF EXISTS prevent_immutable_mutation()",)
